### ISSUE TITLE
Poller exception when getting a new configuration

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#1007]
Sometimes an exception when receiving a new configuration .... this only happens on the `develop+environment` new branch:
```
[2018-03-23 08:40:39] WARNING: [poller-smoove.alignak.http.generic_interface] My Arbiter wants me to wait for a new configuration.
[2018-03-23 08:40:39] ERROR: [poller-smoove.alignak.daemon] I got an unrecoverable error. I have to exit.
[2018-03-23 08:40:39] ERROR: [poller-smoove.alignak.daemon] -----
[2018-03-23 08:40:39] ERROR: [poller-smoove.alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2018-03-23 08:40:39] ERROR: [poller-smoove.alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configuration,...
)
[2018-03-23 08:40:39] CRITICAL: [poller-smoove.alignak.daemon] -----
[2018-03-23 08:40:39] CRITICAL: [poller-smoove.alignak.daemon] Exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/satellite.py", line 1053, in main
    self.do_main_loop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 1015, in do_main_loop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/satellite.py", line 905, in do_loop_turn
    self.get_new_actions()
  File "/usr/local/lib/python2.7/site-packages/alignak/satellite.py", line 734, in get_new_actions
    self.do_get_new_actions()
  File "/usr/local/lib/python2.7/site-packages/alignak/satellite.py", line 752, in do_get_new_actions
    for scheduler_link_uuid in self.schedulers:
RuntimeError: dictionary changed size during iteration

[2018-03-23 08:40:39] CRITICAL: [poller-smoove.alignak.daemon] Back trace of the error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/satellite.py", line 1053, in main
    self.do_main_loop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 1015, in do_main_loop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/satellite.py", line 905, in do_loop_turn
    self.get_new_actions()
  File "/usr/local/lib/python2.7/site-packages/alignak/satellite.py", line 734, in get_new_actions
    self.do_get_new_actions()
  File "/usr/local/lib/python2.7/site-packages/alignak/satellite.py", line 752, in do_get_new_actions
    for scheduler_link_uuid in self.schedulers:
RuntimeError: dictionary changed size during iteration


```

**Comment by mohierf** [comment]
Same catched in the receiver daemon:
```
[2018-04-11 17:35:18] WARNING: [receiver-master.alignak.http.generic_interface] My Arbiter wants me to wait for a new configuration.
[2018-04-11 17:35:18] ERROR: [receiver-master.alignak.daemon] I got an unrecoverable error. I have to exit.
[2018-04-11 17:35:18] ERROR: [receiver-master.alignak.daemon] -----
[2018-04-11 17:35:18] ERROR: [receiver-master.alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2018-04-11 17:35:18] ERROR: [receiver-master.alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configuration,..
.)
[2018-04-11 17:35:18] CRITICAL: [receiver-master.alignak.daemon] -----
[2018-04-11 17:35:18] CRITICAL: [receiver-master.alignak.daemon] Exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 363, in main
    self.do_main_loop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 1018, in do_main_loop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 315, in do_loop_turn
    self.push_external_commands_to_schedulers()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 248, in push_external_commands_to_schedulers
    for scheduler_link_uuid in self.schedulers:
RuntimeError: dictionary changed size during iteration

[2018-04-11 17:35:18] CRITICAL: [receiver-master.alignak.daemon] Back trace of the error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 363, in main
    self.do_main_loop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 1018, in do_main_loop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 315, in do_loop_turn
    self.push_external_commands_to_schedulers()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 248, in push_external_commands_to_schedulers
    for scheduler_link_uuid in self.schedulers:
RuntimeError: dictionary changed size during iteration

```

**Comment by mohierf** [comment]
Looks fixed as of now
