### ISSUE TITLE
Scheduler exception: NoneType' object has no attribute 'notification_period

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#1018]
```
[2018-04-27 07:05:30] INFO: [scheduler-fdj.alignak.scheduler] Enabling the scheduling loop...
[2018-04-27 07:05:30] INFO: [scheduler-fdj.alignak.http.scheduler_interface] A new broker just connected : broker-fdj
[2018-04-27 07:05:30] INFO: [scheduler-fdj.alignak.scheduler] Filling initial broks for: broker-fdj (707575e98e124e3584a46e4cada547e8)
[2018-04-27 07:05:30] ERROR: [scheduler-fdj.alignak.scheduler] Item with id 5cdd278d76544ad49a2d2679fe78e7fb not found!
[2018-04-27 07:05:30] ERROR: [scheduler-fdj.alignak.daemon] I got an unrecoverable error. I have to exit.
[2018-04-27 07:05:30] ERROR: [scheduler-fdj.alignak.daemon] -----
[2018-04-27 07:05:30] ERROR: [scheduler-fdj.alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2018-04-27 07:05:30] ERROR: [scheduler-fdj.alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, co
nfiguration,...)
[2018-04-27 07:05:30] CRITICAL: [scheduler-fdj.alignak.daemon] -----
[2018-04-27 07:05:30] CRITICAL: [scheduler-fdj.alignak.daemon] Exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 547, in main
    self.do_main_loop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 1018, in do_main_loop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 270, in do_loop_turn
    self.sched.run()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 2376, in run
    fun()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 1757, in consume_results
    notification_period = self.timeperiods.items.get(item.notification_period, None)
AttributeError: 'NoneType' object has no attribute 'notification_period'

[2018-04-27 07:05:30] CRITICAL: [scheduler-fdj.alignak.daemon] Back trace of the error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 547, in main
    self.do_main_loop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 1018, in do_main_loop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 270, in do_loop_turn
    self.sched.run()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 2376, in run
    fun()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 1757, in consume_results
    notification_period = self.timeperiods.items.get(item.notification_period, None)
AttributeError: 'NoneType' object has no attribute 'notification_period'

[2018-04-27 07:05:41] INFO: [scheduler-fdj.alignak.scheduler] [scheduler-fdj scheduler] Created 15350 initial broks for broker-fdj
[2018-04-27 07:05:41] INFO: [scheduler-fdj.alignak.http.scheduler_interface] A new broker just connected : broker-master
[2018-04-27 07:05:41] INFO: [scheduler-fdj.alignak.scheduler] Filling initial broks for: broker-master (ccc4223bd15f40ef80279fa4aa78c48c)
[2018-04-27 07:05:58] INFO: [scheduler-fdj.alignak.scheduler] [scheduler-fdj scheduler] Created 15350 initial broks for broker-master

```

**Comment by mohierf** [comment]
Fixed with 2.0
