### ISSUE TITLE
Scheduler which received no hosts exception

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#1032]
Scheduler which received no hosts in its configuration may raise:
```
[2018-08-12 09:02:41] INFO: [scheduler-north.alignak.satellite] My Alignak instance: My demo Alignak
[2018-08-12 09:02:41] WARNING: [scheduler-north.alignak.daemons.schedulerdaemon] No managed configuration received from arbiter
[2018-08-12 09:02:41] INFO: [scheduler-north.alignak.daemons.schedulerdaemon] Monitored configuration None received at 1534057361. Un-serialized in 0 secs
[2018-08-12 09:02:41] INFO: [scheduler-north.alignak.daemons.schedulerdaemon] Scheduler received configuration : None
[2018-08-12 09:02:41] ERROR: [scheduler-north.alignak.daemons.schedulerdaemon] Missing pollers in the configuration!
[2018-08-12 09:02:41] ERROR: [scheduler-north.alignak.daemons.schedulerdaemon] Missing reactionners in the configuration!
[2018-08-12 09:02:41] ERROR: [scheduler-north.alignak.daemons.schedulerdaemon] Missing brokers in the configuration!
[2018-08-12 09:02:41] INFO: [scheduler-north.alignak.daemons.schedulerdaemon] I do not have modules
[2018-08-12 09:02:41] INFO: [scheduler-north.alignak.daemons.schedulerdaemon] Initializing connection with my satellites:
[2018-08-12 09:02:41] INFO: [scheduler-north.alignak.daemon] pause duration: 0.50
[2018-08-12 09:02:41] INFO: [scheduler-north.alignak.daemon] maximum expected loop duration: 1.00
[2018-08-12 09:02:41] INFO: [scheduler-north.alignak.scheduler] Disabling the scheduling loop...
[2018-08-12 09:02:41] INFO: [scheduler-north.alignak.daemon] starting main loop: 1534057361.71
[2018-08-12 09:02:41] INFO: [scheduler-north.alignak.daemons.schedulerdaemon] First scheduling launched
[2018-08-12 09:02:41] CRITICAL: [scheduler-north.alignak.daemon] -----
Exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 592, in main
    self.do_main_loop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 1067, in do_main_loop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 255, in do_loop_turn
    self.sched.schedule()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 1912, in schedule
    for elt in elements:
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 337, in all_my_hosts_and_services
    for what in (self.hosts, self.services):
AttributeError: 'Scheduler' object has no attribute 'hosts'
```

**Comment by mohierf** [comment]
Should be fixed in 2.0
