### ISSUE TITLE
Arbiter /problems is raising an error 500

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#1041]
```
curl http://127.0.0.1:7770/problems
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 631, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 695, in _do_respond
    response.finalize()
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 937, in finalize
    content = self.collapse_body()
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 898, in collapse_body
    for chunk in self.body:
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cpcompat.py", line 124, in json_encode
    for chunk in _json_encode(value):
  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 698, in _iterencode
    o = _default(o)
  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 268, in default
    o.__class__.__name__)
TypeError: Object of type method is not JSON serializable
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 15.0.0</a>
      </span>
    </div>
    </body>
</html>

```

**Comment by mohierf** [comment]
To get the current known problems, one must use the `monitoring_problems` endpoint and not the `problems` endpoint !
