### ISSUE TITLE
Configuration check exception, for realms

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#1103]
Got this:
```
[2019-05-09 14:53:09] INFO: [arbiter-master.alignak.objects.config] Checked
[2019-05-09 14:53:09] CRITICAL: [arbiter-master.alignak.daemon] -----
Exception: 'South'
Back trace of the error:
Traceback (most recent call last):
  File "/home/fmohier/PycharmProjects/alignak/alignak/daemons/arbiterdaemon.py", line 2117, in main
    self.load_monitoring_config_file()
  File "/home/fmohier/PycharmProjects/alignak/alignak/daemons/arbiterdaemon.py", line 760, in load_monitoring_config_file
    self.conf.is_correct()
  File "/home/fmohier/PycharmProjects/alignak/alignak/objects/config.py", line 2499, in is_correct
    realm = self.realms[item.realm]
  File "/home/fmohier/PycharmProjects/alignak/alignak/objects/item.py", line 789, in __getitem__
    return self.items[key] if key else None
KeyError: 'South'

```

during the configuration check.

**Comment by mohierf** [comment]
This happen in a business rule when an unknown realm is used in the configuration
