### ISSUE TITLE
Module inner metrics raised an exception

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#1104]
I noticed:
```
[2019-05-14 08:30:24] ERROR: [broker-master.alignak.module.inner-metrics] initialization, test connection failed. Error: [Errno 111] Connection refused
[2019-05-14 08:30:24] ERROR: [broker-master.alignak.modulesmanager] The module instance inner-metrics raised an exception on initialization: local variable 'connections' referenced before assignment, I remove it!
[2019-05-14 08:30:24] ERROR: [broker-master.alignak.modulesmanager] local variable 'connections' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/alignak/modulesmanager.py", line 189, in try_instance_init
    if not instance.init():
  File "/usr/local/lib/python3.6/site-packages/alignak/modules/inner_metrics.py", line 294, in init
    return connections
UnboundLocalError: local variable 'connections' referenced before assignment

```

**Comment by mohierf** [comment]
This happen only when all the configured connections fail to establish! Must be fixed with a proper variable initialization....
