### ISSUE TITLE
Scheduler fatal error

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#241]
I have a fatal error 

```
Traceback (most recent call last):
  File "/usr/local/bin/alignak-scheduler", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/alignak/bin/alignak_scheduler.py", line 139, in main
    daemon.main()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 391, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 326, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 215, in do_loop_turn
    self.sched.run()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 2010, in run
    fun()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 583, in clean_queues
    id_to_del_broks = [c_id for c_id in broks if c_id < id_max - max_broks]
RuntimeError: dictionary changed size during iteration
```

I have 17k services and 1k hosts

**Comment by ddurieux** [comment]
Add a test
