### ISSUE TITLE
Alignak start - directory access problem

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#247]
After installing from source code, Alignak does not start when launched from the `alignak` user account: 
```
[1447681997] WARNING: [Alignak] Cannot call the additional groups setting with initgroups (Operation not permitted)
[1447681997] CRITICAL: [Alignak] I got an unrecoverable error. I have to exit.
[1447681997] CRITICAL: [Alignak] You can get help at https://github.com/Alignak-monitoring/alignak
[1447681997] CRITICAL: [Alignak] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1447681997] CRITICAL: [Alignak] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/arbiterdaemon.py", line 578, in main
    self.do_daemon_init_and_start()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 651, in do_daemon_init_and_start
    self.check_parallel_run()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 477, in check_parallel_run
    self.__open_pidfile()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 461, in __open_pidfile
    raise InvalidPidFile(err)
InvalidPidFile: [Errno 13] Permission denied: u'/usr/local/var/run/alignak/arbiterd.pid'

Traceback (most recent call last):
  File "/usr/local/bin/alignak-arbiter", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/alignak/bin/alignak_arbiter.py", line 128, in main
    daemon.main()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/arbiterdaemon.py", line 578, in main
    self.do_daemon_init_and_start()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 651, in do_daemon_init_and_start
    self.check_parallel_run()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 477, in check_parallel_run
    self.__open_pidfile()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 461, in __open_pidfile
    raise InvalidPidFile(err)
alignak.daemon.InvalidPidFile: [Errno 13] Permission denied: u'/usr/local/var/run/alignak/arbiterd.pid'
```

**Comment by ddurieux** [comment]
Try add right to alignak user to folder /usr/local/var/run/alignak

I will try to fix that

**Comment by Seb-Solon** [comment]
As far as I know  /usr/local/ is only root writable and default config path are pointing to this. So maybe it's the config generation in setup hook that fails.

**Comment by ddurieux** [comment]
You mean we will have /var/run/alignak instead /usr/local/var/run/alignak ?

**Comment by Seb-Solon** [comment]
No of course. All those are system write only so... I don't know where we can put the run path if it's not /usr/local.

**Comment by ddurieux** [comment]
I think we can put:

* /var/log/alignak instead /usr/local/var/log/alignak
* /var/run/alignak instead /usr/lcoal/var/run/alignak

It can make sense

**Comment by mohierf** [comment]
The following paths:
- `/var/log/alignak`
- `/var/run/alignak`

are much more usual path than relocating everything in `/usr/local ...`, no?

Same as for `/etc/alignak` rather than `/usr/local/etc/alignak`...

**Comment by ddurieux** [comment]
For log and run yes it's for all linux / BSD, but not for etc

**Comment by mohierf** [comment]
Same access right problem when trying to launch with `sudo ...`: 
```
[1447685035] CRITICAL: [Alignak] I got an unrecoverable error. I have to exit.
[1447685035] CRITICAL: [Alignak] You can get help at https://github.com/Alignak-monitoring/alignak
[1447685035] CRITICAL: [Alignak] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1447685035] CRITICAL: [Alignak] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/arbiterdaemon.py", line 578, in main
    self.do_daemon_init_and_start()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 651, in do_daemon_init_and_start
    self.check_parallel_run()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 477, in check_parallel_run
    self.__open_pidfile()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 461, in __open_pidfile
    raise InvalidPidFile(err)
InvalidPidFile: [Errno 13] Permission denied: u'/usr/local/var/run/alignak/arbiterd.pid'

Traceback (most recent call last):
  File "/usr/local/bin/alignak-arbiter", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/alignak/bin/alignak_arbiter.py", line 128, in main
    daemon.main()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/arbiterdaemon.py", line 578, in main
    self.do_daemon_init_and_start()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 651, in do_daemon_init_and_start
    self.check_parallel_run()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 477, in check_parallel_run
    self.__open_pidfile()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 461, in __open_pidfile
    raise InvalidPidFile(err)
alignak.daemon.InvalidPidFile: [Errno 13] Permission denied: u'/usr/local/var/run/alignak/arbiterd.pid'
```

Current rights: 
```
alignak@Alignak:~/alignak$ ls -alht /usr/local/var/run
total 12K
drwxr-xr-x 3 root root 4.0K Nov 16 12:08 .
drwxr-xr-x 5 root root 4.0K Nov 16 12:08 ..
drwxr-xr-x 2 root root 4.0K Nov 16 12:08 alignak
```

**Comment by ddurieux** [comment]
Yes, need have right alignak on /usr/local/var/run/alignak

**Comment by mohierf** [comment]
The setup script should manage this ..

When installing with `sudo python setup.py install`, one should be able to run alignak with `sudo alignak_run.sh` *(assuming that `alignak_run.sh` is a schell script that launches all the daemons)*.

**Comment by Seb-Solon** [comment]
That basically what we did not want when rework setup.py: make system change in it. sudo setup.py will put alignak as defaut user. But if you setup install with a normal user it should work

**Comment by mohierf** [comment]
@ddurieux @Seb-Solon 

What is the final decision about this ?

Here is a fresh installation on an Ubuntu:
```
    sudo apt-get update && sudo apt-get upgrade
    sudo apt-get install python2.7 python2.7-dev python-pip
    sudo pip install alignak
    sudo find / -name alignak:
        /usr/local/lib/python2.7/dist-packages/alignak
        /usr/local/var/lib/alignak
        /usr/local/var/log/alignak
        /usr/local/var/run/alignak
        /usr/local/etc/alignak
        /usr/local/etc/default/alignak
        /usr/local/etc/init.d/alignak
    ll /usr/local/var/lib/alignak/
        total 8
        drwxr-xr-x 2 root root 4096 Sep 13 06:23 ./
        drwxr-xr-x 3 root root 4096 Sep 13 06:23 ../
    ll /usr/local/var/log/alignak/
        total 8
        drwxr-xr-x 2 root root 4096 Sep 13 06:23 ./
        drwxr-xr-x 3 root root 4096 Sep 13 06:23 ../
    ll /usr/local/var/run/alignak/
        total 8
        drwxr-xr-x 2 root root 4096 Sep 13 06:23 ./
        drwxr-xr-x 3 root root 4096 Sep 13 06:23 ../
    ll /usr/local/etc/alignak/
        total 28
        drwxr-xr-x 5 root root 4096 Sep 13 06:23 ./
        drwxr-xr-x 5 root root 4096 Sep 13 06:23 ../
        -rw-r--r-- 1 root root 4269 Sep 13 06:23 alignak.cfg
        drwxr-xr-x 6 root root 4096 Sep 13 06:23 arbiter_cfg/
        drwxr-xr-x 2 root root 4096 Sep 13 06:23 certs/
        drwxr-xr-x 2 root root 4096 Sep 13 06:23 daemons/
    ll /usr/local/etc/default/alignak
        -rw-r--r-- 1 root root 4396 Sep 13 06:23 /usr/local/etc/default/alignak
    ll /usr/local/etc/init.d/alignak
        -rwxr-xr-x 1 root root 14261 Sep 13 06:23 /usr/local/etc/init.d/alignak*
```

And then, the *entry point* file:
```
    cat /usr/local/etc/default/alignak
        # Copyright (C) 2015-2015: Alignak team, see AUTHORS.txt file for contributors
        #
        # This file is part of Alignak.
        #
        # Alignak is free software: you can redistribute it and/or modify
        # it under the terms of the GNU Affero General Public License as published by
        # the Free Software Foundation, either version 3 of the License, or
        # (at your option) any later version.
        #
        # Alignak is distributed in the hope that it will be useful,
        # but WITHOUT ANY WARRANTY; without even the implied warranty of
        # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        # GNU Affero General Public License for more details.
        #
        # You should have received a copy of the GNU Affero General Public License
        # along with Alignak.  If not, see <http://www.gnu.org/licenses/>.
        #
        #
        # This file incorporates work covered by the following copyright and
        # permission notice:
        #
        #  Copyright (C) 2009-2014:
        #     Gabes Jean, naparuba@gmail.com
        #     Gerhard Lausser, Gerhard.Lausser@consol.de
        #     Gregory Starck, g.starck@gmail.com
        #     Hartmut Goebel, h.goebel@goebel-consult.de
        #
        #  This file is part of Shinken.
        #
        #  Shinken is free software: you can redistribute it and/or modify
        #  it under the terms of the GNU Affero General Public License as published by
        #  the Free Software Foundation, either version 3 of the License, or
        #  (at your option) any later version.
        #
        #  Shinken is distributed in the hope that it will be useful,
        #  but WITHOUT ANY WARRANTY; without even the implied warranty of
        #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        #  GNU Affero General Public License for more details.
        #
        #  You should have received a copy of the GNU Affero General Public License
        #  along with Shinken.  If not, see <http://www.gnu.org/licenses/>.


        # /etc/default/alignak
        # $ETC$ is where we put all configuration files
        # $VAR$ is where we put some variables files (replaced by $RUN$ and $LOG$ for now)
        # $RUN$ is where we put pid files
        # $LOG$ is where we put log files
        # $SCRIPTS_BIN$ is where the launch scripts will be send


        ## These vars will override the hardcoded ones in init script ##
        ETC=/usr/local/etc/alignak
        VAR=/usr/local/var/lib/alignak
        BIN=/usr/local/bin
        RUN=/usr/local/var/run/alignak
        LOG=/usr/local/var/log/alignak


        ### ARBITER PART ###
        # location of the alignak configuration file
        # Please update $ETC$ instead of this one.
        ALIGNAKCFG="$ETC/alignak.cfg"

        # We got 2 configs because tools like Centreon don't generate all
        # configuration (only the alignak.cfg part)
        #ALIGNAKSPECIFICCFG="$ETC/alignak-specific.cfg"

        # The command to launch
        ARBITERDAEMON=$BIN/alignak-arbiter

        #The ARBITER PID
        if [ -r $ALIGNAKCFG ] ; then
        tmppid=`grep 'lock_file=' $ALIGNAKCFG | grep -v '#' | tail -n 1 | awk -F '=' '{print $2}'`
        ARBITERPID=${tmppid-$RUN/arbiterd.pid}
        else
        ARBITERPID="$RUN/arbiterd.pid"
        fi

        ARBITERDEBUGFILE="$LOG/arbiter-debug.log"


        ### SCHEDULER PART ###
        # location of the scheduler daemon configuration
        SCHEDULERCFG="$ETC/daemons/schedulerd.ini"

        # The command to launch
        SCHEDULERDAEMON=$BIN/alignak-scheduler

        # The SCHEDULER PID
        SCHEDULERPID="$RUN/schedulerd.pid"

        SCHEDULERDEBUGFILE="$LOG/scheduler-debug.log"


        ### POLLER PART ###
        # location of the poller daemon configuration
        POLLERCFG="$ETC/daemons/pollerd.ini"

        # The command to launch
        POLLERDAEMON=$BIN/alignak-poller

        # The poller pid
        POLLERPID="$RUN/pollerd.pid"

        POLLERDEBUGFILE="$LOG/poller-debug.log"


        ### REACTIONNER PART ###
        # location of the reactionner daemon configuration
        REACTIONNERCFG="$ETC/daemons/reactionnerd.ini"

        # The command to launch
        REACTIONNERDAEMON=$BIN/alignak-reactionner

        #The reactionner pid
        REACTIONNERPID="$RUN/reactionnerd.pid"

        REACTIONNERDEBUGFILE="$LOG/reactionner-debug.log"


        ### BROKER PART ###
        # location of the broker daemon configuration
        BROKERCFG="$ETC/daemons/brokerd.ini"

        # The command to launch
        BROKERDAEMON=$BIN/alignak-broker

        # The broker pid
        BROKERPID="$RUN/brokerd.pid"

        BROKERDEBUGFILE="$LOG/broker-debug.log"


        ### RECEIVER PART ###
        # location of the broker receiver configuration
        RECEIVERCFG="$ETC/daemons/receiverd.ini"

        # The command to launch
        RECEIVERDAEMON=$BIN/alignak-receiver

        #The receiver pid
        RECEIVERPID="$RUN/receiverd.pid"

        RECEIVERDEBUGFILE="$LOG/receiver-debug.log"



        # nicelevel to run alignak daemon with
        NICENESS=5

        # user/group for the var/run rights
        ALIGNAKUSER=alignak
        ALIGNAKGROUP=alignak
        HOME=`grep ^$ALIGNAKUSER: /etc/passwd | cut -d: -f 6`
```

**Comment by mohierf** [comment]
What I propose to clean and finish this: 

- [ ] test if an `alignak` user exists before installing the files. If it does not exist, exit the installation with an information message
- [ ] on script end, set the correct user rights on the directories for the `alignak` user
- [ ] include a `$PLUGINSDIR$` variable in the *default/alignak* file as discussed in #249 and #255 

@ddurieux @Seb-Solon I start those modifications now...
