### ISSUE TITLE
Error on get_raw_stats API of arbiter

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#267]
In arbiter, we don't have get_raw_stats route, so it use generic_interface function but we have error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Donnees/developpement/sources/Alignak-monitoring/alignak/alignak/http/generic_interface.py", line 281, in get_raw_stats
    for sched_id in app.schedulers:
AttributeError: 'Arbiter' object has no attribute 'schedulers'
```

I think add a route in arbiter_interface but what data we can offer? 
* list of satellites (scheduler, poller, broker...)
* Number of config objects (number of hosts, number of services)

If you have other ideas ;)

**Comment by ddurieux** [comment]
Bug fixed
