### ISSUE TITLE
Ubuntu deb package installation error:  KeyError: 'alignak'

### ISSUE THREAD

**Issue by gourneau** [Alignak-monitoring/alignak#272]
When installing alignak-all 0.1-1 on Ubuntu 14.04 , this is the output

```
root@ubuntu:/home/josh# aptitude install alignak-all
The following NEW packages will be installed:
  alignak-all bsd-mailx{a} libjs-jquery{a} libjs-sphinxdoc{a} libjs-underscore{a} postfix{a} python-cherrypy3{a} 
  python-pbr{a} python-pyasn1{a} python-repoze.lru{a} python-routes{a} python-setproctitle{a} python-termcolor{a} 
  python-ujson{a} python-webob{a} 
The following packages will be upgraded:
  python-requests python-urllib3 
2 packages upgraded, 15 newly installed, 0 to remove and 265 not upgraded.
Need to get 3,194 kB of archives. After unpacking 30.3 MB will be used.
Do you want to continue? [Y/n/?] y
WARNING: untrusted versions of the following packages will be installed!

Untrusted packages could compromise your system's security.
You should only proceed with the installation if you are certain that
this is what you want to do.

  alignak-all python-urllib3 python-ujson python-requests 

Do you want to ignore this warning and proceed anyway?
To continue, enter "Yes"; to abort, enter "No": yes
Get: 1 http://alignak-monitoring.github.io/repos/deb/ trusty/main python-urllib3 all 1.12-1 [65.0 kB]
Get: 2 http://us.archive.ubuntu.com/ubuntu/ trusty/universe python-termcolor all 1.1.0-1 [5,326 B]
Get: 3 http://us.archive.ubuntu.com/ubuntu/ trusty/main python-pbr all 0.7.0-0ubuntu2 [36.1 kB]
Get: 4 http://alignak-monitoring.github.io/repos/deb/ trusty/main python-requests all 2.8.1-1 [67.8 kB]
Get: 5 http://alignak-monitoring.github.io/repos/deb/ trusty/main python-ujson amd64 1.33-1+b1 [20.8 kB]
Get: 6 http://us.archive.ubuntu.com/ubuntu/ trusty/main python-repoze.lru all 0.6-4 [11.3 kB]
Get: 7 http://alignak-monitoring.github.io/repos/deb/ trusty/main alignak-all all 0.1-1~trusty [280 kB]
Get: 8 http://us.archive.ubuntu.com/ubuntu/ trusty/main libjs-jquery all 1.7.2+dfsg-2ubuntu1 [78.8 kB]
Get: 9 http://us.archive.ubuntu.com/ubuntu/ trusty/main libjs-underscore all 1.4.4-2ubuntu1 [45.6 kB]
Get: 10 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main libjs-sphinxdoc all 1.2.2+dfsg-1ubuntu1.1 [41.4 kB]
Get: 11 http://us.archive.ubuntu.com/ubuntu/ trusty/main python-routes all 2.0-1build1 [76.6 kB]
Get: 12 http://us.archive.ubuntu.com/ubuntu/ trusty/main python-cherrypy3 all 3.2.2-4ubuntu5 [1,209 kB]
Get: 13 http://us.archive.ubuntu.com/ubuntu/ trusty/universe python-setproctitle amd64 1.0.1-1ubuntu1 [9,486 B]       
Get: 14 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main postfix amd64 2.11.0-1ubuntu1 [1,084 kB]             
Get: 15 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main bsd-mailx amd64 8.1.2-0.20131005cvs-1ubuntu0.14.04.1 [60.1 kB]
Get: 16 http://us.archive.ubuntu.com/ubuntu/ trusty/main python-pyasn1 all 0.1.7-1ubuntu2 [44.2 kB]                   
Get: 17 http://us.archive.ubuntu.com/ubuntu/ trusty/main python-webob all 1.3.1-1 [57.9 kB]                           
Fetched 3,194 kB in 10s (317 kB/s)                                                                                    
Preconfiguring packages ...
Selecting previously unselected package python-termcolor.
(Reading database ... 168035 files and directories currently installed.)
Preparing to unpack .../python-termcolor_1.1.0-1_all.deb ...
Unpacking python-termcolor (1.1.0-1) ...
Selecting previously unselected package python-pbr.
Preparing to unpack .../python-pbr_0.7.0-0ubuntu2_all.deb ...
Unpacking python-pbr (0.7.0-0ubuntu2) ...
Selecting previously unselected package python-repoze.lru.
Preparing to unpack .../python-repoze.lru_0.6-4_all.deb ...
Unpacking python-repoze.lru (0.6-4) ...
Selecting previously unselected package libjs-jquery.
Preparing to unpack .../libjs-jquery_1.7.2+dfsg-2ubuntu1_all.deb ...
Unpacking libjs-jquery (1.7.2+dfsg-2ubuntu1) ...
Selecting previously unselected package libjs-underscore.
Preparing to unpack .../libjs-underscore_1.4.4-2ubuntu1_all.deb ...
Unpacking libjs-underscore (1.4.4-2ubuntu1) ...
Selecting previously unselected package libjs-sphinxdoc.
Preparing to unpack .../libjs-sphinxdoc_1.2.2+dfsg-1ubuntu1.1_all.deb ...
Unpacking libjs-sphinxdoc (1.2.2+dfsg-1ubuntu1.1) ...
Selecting previously unselected package python-routes.
Preparing to unpack .../python-routes_2.0-1build1_all.deb ...
Unpacking python-routes (2.0-1build1) ...
Selecting previously unselected package python-cherrypy3.
Preparing to unpack .../python-cherrypy3_3.2.2-4ubuntu5_all.deb ...
Unpacking python-cherrypy3 (3.2.2-4ubuntu5) ...
Preparing to unpack .../python-urllib3_1.12-1_all.deb ...
Unpacking python-urllib3 (1.12-1) over (1.7.1-1ubuntu3) ...
Preparing to unpack .../python-requests_2.8.1-1_all.deb ...
Unpacking python-requests (2.8.1-1) over (2.2.1-1ubuntu0.3) ...
Selecting previously unselected package python-setproctitle.
Preparing to unpack .../python-setproctitle_1.0.1-1ubuntu1_amd64.deb ...
Unpacking python-setproctitle (1.0.1-1ubuntu1) ...
Selecting previously unselected package python-ujson.
Preparing to unpack .../python-ujson_1.33-1+b1_amd64.deb ...
Unpacking python-ujson (1.33-1+b1) ...
Selecting previously unselected package alignak-all.
Preparing to unpack .../alignak-all_0.1-1~trusty_all.deb ...
Unpacking alignak-all (0.1-1~trusty) ...
Selecting previously unselected package postfix.
Preparing to unpack .../postfix_2.11.0-1ubuntu1_amd64.deb ...
Unpacking postfix (2.11.0-1ubuntu1) ...
Selecting previously unselected package bsd-mailx.
Preparing to unpack .../bsd-mailx_8.1.2-0.20131005cvs-1ubuntu0.14.04.1_amd64.deb ...
Unpacking bsd-mailx (8.1.2-0.20131005cvs-1ubuntu0.14.04.1) ...
Selecting previously unselected package python-pyasn1.
Preparing to unpack .../python-pyasn1_0.1.7-1ubuntu2_all.deb ...
Unpacking python-pyasn1 (0.1.7-1ubuntu2) ...
Selecting previously unselected package python-webob.
Preparing to unpack .../python-webob_1.3.1-1_all.deb ...
Unpacking python-webob (1.3.1-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for doc-base (0.10.5) ...
Processing 2 added doc-base files...
Processing triggers for ureadahead (0.100.0-16) ...
Processing triggers for ufw (0.34~rc-0ubuntu2) ...
Setting up python-termcolor (1.1.0-1) ...
Setting up python-pbr (0.7.0-0ubuntu2) ...
Setting up python-repoze.lru (0.6-4) ...
Setting up libjs-jquery (1.7.2+dfsg-2ubuntu1) ...
Setting up libjs-underscore (1.4.4-2ubuntu1) ...
Setting up libjs-sphinxdoc (1.2.2+dfsg-1ubuntu1.1) ...
Setting up python-routes (2.0-1build1) ...
Setting up python-cherrypy3 (3.2.2-4ubuntu5) ...
Setting up python-urllib3 (1.12-1) ...
Setting up python-requests (2.8.1-1) ...
Setting up python-setproctitle (1.0.1-1ubuntu1) ...
Setting up python-ujson (1.33-1+b1) ...
Setting up alignak-all (0.1-1~trusty) ...
Adding group `nagios' (GID 127) ...
Done.
Adding user `alignak' to group `nagios' ...
Adding user alignak to group nagios
Done.
Setting up postfix (2.11.0-1ubuntu1) ...
Adding group `postfix' (GID 128) ...
Done.
Adding system user `postfix' (UID 118) ...
Adding new user `postfix' (UID 118) with group `postfix' ...
Not creating home directory `/var/spool/postfix'.
Creating /etc/postfix/dynamicmaps.cf
Adding tcp map entry to /etc/postfix/dynamicmaps.cf
Adding sqlite map entry to /etc/postfix/dynamicmaps.cf
Adding group `postdrop' (GID 129) ...
Done.
setting myhostname: ubuntu
setting alias maps
setting alias database
mailname is not a fully qualified domain name.  Not changing /etc/mailname.
setting destinations: ubuntu, localhost.localdomain, , localhost
setting relayhost: 
setting mynetworks: 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
setting mailbox_size_limit: 0
setting recipient_delimiter: +
setting inet_interfaces: all
setting inet_protocols: all
/etc/aliases does not exist, creating it.
WARNING: /etc/aliases exists, but does not have a root alias.

Postfix is now set up with a default configuration.  If you need to make 
changes, edit
/etc/postfix/main.cf (and others) as needed.  To view Postfix configuration
values, see postconf(1).

After modifying main.cf, be sure to run '/etc/init.d/postfix reload'.

Running newaliases
 * Stopping Postfix Mail Transport Agent postfix                                                               [ OK ] 
 * Starting Postfix Mail Transport Agent postfix                                                               [ OK ] 
Setting up python-pyasn1 (0.1.7-1ubuntu2) ...
Error processing line 2 of /usr/lib/python2.7/dist-packages/alignak-0.1-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python2.7/site.py", line 158, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'alignak'

Remainder of file ignored
Setting up python-webob (1.3.1-1) ...
Error processing line 2 of /usr/lib/python2.7/dist-packages/alignak-0.1-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python2.7/site.py", line 158, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'alignak'

Remainder of file ignored
Processing triggers for ufw (0.34~rc-0ubuntu2) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up bsd-mailx (8.1.2-0.20131005cvs-1ubuntu0.14.04.1) ...
update-alternatives: using /usr/bin/bsd-mailx to provide /usr/bin/mailx (mailx) in auto mode
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
                                         
Current status: 265 updates [-2].
```

The section that is concerning is 

```
Setting up python-pyasn1 (0.1.7-1ubuntu2) ...
Error processing line 2 of /usr/lib/python2.7/dist-packages/alignak-0.1-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python2.7/site.py", line 158, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'alignak'

Remainder of file ignored
Setting up python-webob (1.3.1-1) ...
Error processing line 2 of /usr/lib/python2.7/dist-packages/alignak-0.1-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python2.7/site.py", line 158, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'alignak'

```

**Comment by Seb-Solon** [comment]
Hi,

Can you give a try with the last build? https://alignak-monitoring.github.io/build/ubuntu_14/alignak-all_0.1-1.1449701312.924c778_all.deb from https://alignak-monitoring.github.io/download/

I've updated the packaging, I only need to add this package to the repository after. But I would like to be sure it's working for you before

Thanks

**Comment by Seb-Solon** [comment]
Should be fixed by  : 

Alignak-monitoring/alignak-monitoring.github.io@be5511ee2722a73f4bf1625653f7e6048dbe7b7b 
Alignak-monitoring/alignak-packaging@28e2ac2f242a059b8eee2b7b27a5438252e57f85
Alignak-monitoring/alignak-packaging@2b19f0a8e3c134a719c798c08f1b105ec171cc72
Alignak-monitoring/alignak-packaging@369d995992f02ec69d4d7e577114b163539e2c50
Alignak-monitoring/alignak@d8bf7f944bb7feff665e3e1ec966c43c28f31909
