### ISSUE TITLE
Poller stop log exception

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#314]
When stopping a poller daemon:
```
Stopping daemon. Exiting
Traceback (most recent call last):
  File "/root/git/alignak/alignak/log.py", line 110, in emit
    msg = self.format(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 726, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not str
Logged from file log.py, line 287
```

**Comment by mohierf** [comment]
Not reproduced anymore
