### ISSUE TITLE
Loading large configuration

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#369]
When loading a large configuration (), an exception is raised in the Arbiter process when serializing the configuration:

```
[1474897837] INFO: [Alignak] Number of Contacts : 638
[1474897837] INFO: [Alignak] Number of Hosts : 9647
[1474897837] INFO: [Alignak] Number of Services : 56238
[1474897837] INFO: [Alignak] Number of Commands : 1317
[1474897837] INFO: [Alignak] Total number of hosts in all realms: 9647
...
...
...
Configuration loading exception: 
***** Traceback: %s Traceback (most recent call last):
  File "/home/alignak/alignak-backend-import/alignak_backend_import/cfg_to_backend.py", line 223, in __init__
    self.arbiter.load_config_file()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/arbiterdaemon.py", line 399, in load_config_file
    self.conf.prepare_for_sending()
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/config.py", line 1463, in prepare_for_sending
    whole_conf_pack = serialize(self)
  File "/usr/local/lib/python2.7/dist-packages/alignak/misc/serialization.py", line 64, in serialize
    return json.dumps(o_dict, ensure_ascii=False)
MemoryError

```

**Comment by mohierf** [comment]
@Seb-Solon : I think that this one needs your knowledge for serialization ... I found this on SO about this problem: http://stackoverflow.com/questions/24239613/memoryerror-using-json-dumps

**Comment by mohierf** [comment]
Indeed, it seems that the error is due to a lack of memory on my test system. Despite, this exception should be catched to alert about a lack of memory when loading the configuration ?

**Comment by ddurieux** [comment]
Yep, it's a good idea to catch and add explicit message like: _not enough memory on this computer_

**Comment by mohierf** [comment]
Serialization recently refactored. No more problem with this
