### ISSUE TITLE
Human timestamp log

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#397]
When activating `human_timestamp_log=1` in alignak.cfg, one expect to get all daemons log with a human readable data. We get only some human dated logs in arbiter and scheduler log:
```
root@alignakfromscratch:~/git/alignak # tail -f /usr/local/var/log/alignak/*.log

==> /usr/local/var/log/alignak/arbiterd.log <==
[Mon Oct 03 14:05:53 2016] INFO: [Alignak] [reactionner-master] Trying to send configuration to reactionner reactionner-master
[Mon Oct 03 14:05:53 2016] INFO: [Alignak] Configuration sent to reactionner reactionner-master
[Mon Oct 03 14:05:53 2016] INFO: [Alignak] [poller-master] Trying to send configuration to poller poller-master
[Mon Oct 03 14:05:53 2016] INFO: [Alignak] Configuration sent to poller poller-master
[Mon Oct 03 14:05:53 2016] INFO: [Alignak] [broker-master] Trying to send configuration to broker broker-master
[Mon Oct 03 14:05:53 2016] INFO: [Alignak] Configuration sent to broker broker-master
[Mon Oct 03 14:05:53 2016] INFO: [Alignak] [receiver-master] Trying to send configuration to receiver receiver-master
[Mon Oct 03 14:05:53 2016] INFO: [Alignak] Configuration sent to receiver receiver-master
[1475503554] TIMEPERIOD TRANSITION: workhours;-1;1
[1475503554] TIMEPERIOD TRANSITION: 24x7;-1;1

==> /usr/local/var/log/alignak/brokerd.log <==
[1475503554] INFO: [broker-master] We have our schedulers: {u'9e726d663be0458d8f879356bfff4cf4': {'broks': {}, u'data_timeout': 120, u'name': u'scheduler-master', 'last_connection': 0, u'hard_ssl_name_check': False, 'uri': u'http://127.0.0.1:7768/', u'instance_id': u'9dd15475124d47d482461850a8701323', u'hosts': [u'localhost'], 'running_id': 0, u'timeout': 3, u'address': u'127.0.0.1', u'active': True, u'use_ssl': False, u'push_flavor': 882375, u'port': 7768}}
[1475503554] INFO: [broker-master] We have our arbiters: {u'5e848cad21db49d7ba5cdfaa28275360': {'broks': {}, 'last_connection': 0, u'name': u'arbiter-master', u'hard_ssl_name_check': False, 'uri': u'http://127.0.0.1:7770/', 'instance_id': 0, 'running_id': 0, u'address': u'127.0.0.1', u'use_ssl': False, u'port': 7770}}
[1475503554] INFO: [broker-master] We have our pollers: {u'6a5541e5d8614c0c9b0617a9749cf87a': {'broks': {}, u'instance_id': 0, 'last_connection': 0, u'name': u'poller-master', u'poller_tags': [u'None'], u'hard_ssl_name_check': False, 'uri': u'http://127.0.0.1:7771/', u'passive': False, u'secret': u'', u'reactionner_tags': [], 'running_id': 0, u'address': u'127.0.0.1', u'active': True, u'use_ssl': False, u'api_key': u'', u'port': 7771}}
[1475503554] INFO: [broker-master] We have our reactionners: {u'4050ad35df244928b95d652e9bc33a6b': {'broks': {}, u'instance_id': 0, 'last_connection': 0, u'name': u'reactionner-master', u'poller_tags': [], u'hard_ssl_name_check': False, 'uri': u'http://127.0.0.1:7769/', u'passive': False, u'secret': u'', u'reactionner_tags': [u'None'], 'running_id': 0, u'address': u'127.0.0.1', u'active': True, u'use_ssl': False, u'api_key': u'', u'port': 7769}}
[1475503554] INFO: [broker-master] We received modules []
[1475503554] INFO: [broker-master] I correctly loaded the modules: []
[1475503554] INFO: [broker-master] Connection problem to the scheduler scheduler-master: Request error to http://127.0.0.1:7768/fill_initial_broks: HTTP GET not OK: 500 ; text=u'<!DOCTYPE html PUBLIC\n"-//W3C//DTD XHTML 1.0 Transitional//EN"\n"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html>\n<head>\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>\n    <title>500 Internal Server Error</title>\n    <style type="text/css">\n    #powered_by {\n        margin-top: 20px;\n        border-top: 2px solid black;\n        font-style: italic;\n    }\n\n    #traceback {\n        color: red;\n    }\n    </style>\n</head>\n    <body>\n        <h2>500 Internal Server Error</h2>\n        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>\n        <pre id="traceback">Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond\n    response.body = self.handler()\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 220, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/lib/jsontools.py", line 61, in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File "/usr/local/lib/python2.7/site-packages/alignak/http/scheduler_interface.py", line 135, in fill_initial_broks\n    self.app.sched.fill_initial_broks(bname, with_logs=True)\n  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 1466, in fill_initial_broks\n    brok = self.get_program_status_brok()\n  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 1533, in get_program_status_brok\n    "instance_name": self.instance_name,\nAttributeError: \'Scheduler\' object has no attribute \'instance_name\'\n</pre>\n    <div id="powered_by">\n      <span>\n        Powered by <a href="http://www.cherrypy.org">CherryPy 8.1.2</a>\n      </span>\n    </div>\n    </body>\n</html>\n'
[1475503554] INFO: [broker-master] Connection OK to the poller poller-master
[1475503554] INFO: [broker-master] Connection OK to the reactionner reactionner-master
[1475503554] INFO: [broker-master] Connection OK to the receiver receiver-master

==> /usr/local/var/log/alignak/pollerd.log <==
[1475503553] INFO: [Alignak] We have our schedulers: {u'9e726d663be0458d8f879356bfff4cf4': {'wait_homerun': {}, u'data_timeout': 120, u'name': u'scheduler-master', u'hard_ssl_name_check': False, 'uri': u'http://127.0.0.1:7768/', 'actions': {}, u'instance_id': u'9dd15475124d47d482461850a8701323', u'hosts': [u'localhost'], 'running_id': 1475503552.3372512, u'timeout': 3, u'address': u'127.0.0.1', u'active': True, u'use_ssl': False, u'push_flavor': 882375, u'port': 7768, 'con': <alignak.http.client.HTTPClient object at 0x80910b210>}}
[1475503553] INFO: [Alignak] I correctly loaded the modules: []
[1475503553] INFO: [Alignak] [poller-master] Allocating new fork Worker: 8b1237d6716448bea62f63dc400b2ad3
[1475503554] INFO: [Alignak] Cleaning BrokHandler <alignak.log.BrokHandler object at 0x8090d5c50> from logger.handlers..
[1475503554] INFO: [Alignak] [poller-master] Allocating new fork Worker: 25b2ee7f63324a2d8e652fc77e87b72f
[1475503554] INFO: [Alignak] [poller-master] Allocating new fork Worker: 843fd49da12149f79d6a5c3b1435ccec
[1475503554] INFO: [Alignak] Cleaning BrokHandler <alignak.log.BrokHandler object at 0x8090d5c50> from logger.handlers..
[1475503555] INFO: [Alignak] Cleaning BrokHandler <alignak.log.BrokHandler object at 0x8090d5c50> from logger.handlers..
[1475503556] INFO: [Alignak] [poller-master] Allocating new fork Worker: 07bb7f5d0b744ba89ebb2ff41636c32d
[1475503556] INFO: [Alignak] Cleaning BrokHandler <alignak.log.BrokHandler object at 0x8090d5c50> from logger.handlers..

==> /usr/local/var/log/alignak/reactionnerd.log <==
[1475503552] INFO: [Alignak] HTTP main thread: I'm running
[1475503552] INFO: [Alignak] Waiting for initial configuration
[1475503553] INFO: [Alignak] [reactionner-master] Init connection with scheduler-master at http://127.0.0.1:7768/ (3s,120s)
[1475503553] INFO: [Alignak] [reactionner-master] Connection OK with scheduler scheduler-master
[1475503553] INFO: [Alignak] [reactionner-master] Using max workers: 15
[1475503553] INFO: [Alignak] [reactionner-master] Using min workers: 1
[1475503553] INFO: [Alignak] We have our schedulers: {u'9e726d663be0458d8f879356bfff4cf4': {'wait_homerun': {}, u'data_timeout': 120, u'name': u'scheduler-master', u'hard_ssl_name_check': False, 'uri': u'http://127.0.0.1:7768/', 'actions': {}, u'instance_id': u'9dd15475124d47d482461850a8701323', u'hosts': [u'localhost'], 'running_id': 1475503552.3372512, u'timeout': 3, u'address': u'127.0.0.1', u'active': True, u'use_ssl': False, u'push_flavor': 882375, u'port': 7768, 'con': <alignak.http.client.HTTPClient object at 0x80910e110>}}
[1475503553] INFO: [Alignak] I correctly loaded the modules: []
[1475503555] INFO: [Alignak] [reactionner-master] Allocating new fork Worker: 2e6bf3ea39424a93b35aa3defb93fdb5
[1475503555] INFO: [Alignak] Cleaning BrokHandler <alignak.log.BrokHandler object at 0x8090d7b50> from logger.handlers..

==> /usr/local/var/log/alignak/receiverd.log <==
[1475503552] INFO: [Alignak] Creating manager ..
[1475503552] INFO: [Alignak] done.
[1475503552] INFO: [Alignak] Now starting http_daemon thread..
[1475503552] ERROR: [Alignak] Cannot find python lib crypto: stats export is not available
[1475503552] INFO: [Alignak] HTTP main thread: I'm running
[1475503552] INFO: [Alignak] Waiting for initial configuration
[1475503554] INFO: [receiver-master] [receiver-master] Init connection with scheduler-master at http://127.0.0.1:7768/ (3s,120s)
[1475503554] INFO: [receiver-master] [receiver-master] Connection OK with scheduler scheduler-master
[1475503554] INFO: [receiver-master] We received modules []
[1475503554] INFO: [receiver-master] I correctly loaded the modules: []

==> /usr/local/var/log/alignak/schedulerd.log <==
[1475503552] INFO: [Alignak] [scheduler] General interface is at: http://0.0.0.0:7768
[1475503552] INFO: [Alignak] HTTP main thread: I'm running
[1475503552] INFO: [Alignak] Waiting for initial configuration
[1475503554] INFO: [Alignak] A new broker just connected : broker-master
[1475503554] INFO: [Alignak] New configuration received
[Mon Oct 03 14:05:54 2016] INFO: [Alignak] I correctly loaded the modules: []
[Mon Oct 03 14:05:54 2016] INFO: [Alignak] Loading configuration.
[Mon Oct 03 14:05:54 2016] INFO: [Alignak] New configuration loaded
[Mon Oct 03 14:05:54 2016] INFO: [Alignak] [scheduler-master] First scheduling launched
[Mon Oct 03 14:05:54 2016] INFO: [Alignak] [scheduler-master] First scheduling done
[Mon Oct 03 14:05:59 2016] INFO: [Alignak] A new broker just connected : broker-master
[Mon Oct 03 14:05:59 2016] INFO: [Alignak] [scheduler-master] Created 22 initial Broks for broker broker-master

==> /usr/local/var/log/alignak/brokerd.log <==
[1475503559] INFO: [broker-master] Connection OK to the scheduler scheduler-master
```

This function: `logger.set_human_format()` should be called for every daemon ...

**Comment by mohierf** [comment]
Fixed with #427
