### ISSUE TITLE
Freshness check exception

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#404]
```
[1475568005] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[1475568005] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[1475568005] CRITICAL: [alignak.daemon] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1475568005] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/root/git/alignak/alignak/daemons/schedulerdaemon.py", line 372, in main
    self.do_mainloop()
  File "/root/git/alignak/alignak/daemon.py", line 328, in do_mainloop
    self.do_loop_turn()
  File "/root/git/alignak/alignak/daemons/schedulerdaemon.py", line 220, in do_loop_turn
    self.sched.run()
  File "/root/git/alignak/alignak/scheduler.py", line 2076, in run
    fun()
  File "/root/git/alignak/alignak/scheduler.py", line 1777, in check_freshness
    self.checks)
  File "/root/git/alignak/alignak/objects/schedulingitem.py", line 660, in do_check_freshness
    chk.output = "Freshness period expired"
AttributeError: 'NoneType' object has no attribute 'output'
```

**Comment by mohierf** [comment]
Considered as fixed because no more observed when testing passive checks
