### ISSUE TITLE
Arbiter configuration loading exception

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#405]
With a configuration got from the Backend arbiter module, the arbiter raises an exception:
```
[1475572684] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[1475572684] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[1475572684] CRITICAL: [alignak.daemon] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1475572684] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/root/git/alignak/alignak/daemons/arbiterdaemon.py", line 523, in main
    self.setup_alignak_logger()
  File "/root/git/alignak/alignak/daemon.py", line 1200, in setup_alignak_logger
    self.load_config_file()
  File "/root/git/alignak/alignak/daemons/arbiterdaemon.py", line 297, in load_config_file
    self.conf.create_objects(raw_objects)
  File "/root/git/alignak/alignak/objects/config.py", line 1223, in create_objects
    self.create_objects_for_type(raw_objects, o_type)
  File "/root/git/alignak/alignak/objects/config.py", line 1253, in create_objects_for_type
    setattr(self, prop, clss(lst, initial_index))
  File "/root/git/alignak/alignak/objects/item.py", line 761, in __init__
    self.add_items(items, index_items)
  File "/root/git/alignak/alignak/objects/item.py", line 793, in add_items
    self.add_item(i, index_items)
  File "/root/git/alignak/alignak/objects/item.py", line 921, in add_item
    item = self.index_item(item)
  File "/root/git/alignak/alignak/objects/item.py", line 967, in index_item
    item = self.manage_conflict(item, name)
  File "/root/git/alignak/alignak/objects/item.py", line 843, in manage_conflict
    (objcls, name, item.imported_from)
AttributeError: imported_from
```

Probably a problem in the Alignak arbiter module ... to be investigated. At least the Arbiter should catch this exception ...

**Comment by mohierf** [comment]
Indeed it is a duplicate command name for `internal_host_up` or `_echo` self created commands ... they do not have any *imported_from* property when they are created ...
