### ISSUE TITLE
Exception in service dependencies configuration parsing

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#439]
```
Traceback (most recent call last):
  File "/usr/local/bin/alignak-arbiter", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/alignak/bin/alignak_arbiter.py", line 74, in main
    daemon.main()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/arbiterdaemon.py", line 522, in main
    self.load_monitoring_config_file()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/arbiterdaemon.py", line 330, in load_monitoring_config_file
    self.conf.explode()
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/config.py", line 1685, in explode
    self.servicedependencies.explode(self.hostgroups)
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/servicedependency.py", line 231, in explode
    hnames.extend([m.strip() for m in hostgroup.members])
AttributeError: 'Hostgroup' object has no attribute 'members'

```

**Edit:** more information ... this exception occurs when a `service_dependency` is defined as a template or for an host template ...

**Edit:**: this configuration, whereas correct, raises the exception and breaks the configuration parsing:
```
# Services dependencies
define servicedependency{
    hostgroup_name	                    north-hosts
    service_description                 Application
    dependent_service_description       Session, Monitoring
    execution_failure_criteria          o
    notification_failure_criteria       w
    dependency_period                   24x7

    ; explode_hostgroup                   1
}
```

**Comment by mohierf** [comment]
The correct method to get the hosts members of an hostgroup is the *get_hosts()* method ... and not using the `members` property.
