### ISSUE TITLE
Exception on alignak restart

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#444]
When restarting alignak with the init.d scripts:
```
[2016-10-12 05:49:14 CEST] INFO: [alignak.daemons.schedulerdaemon] We have our pollers:
[2016-10-12 05:49:14 CEST] INFO: [alignak.daemons.schedulerdaemon]  - poller-master 
[2016-10-12 05:49:14 CEST] INFO: [alignak.daemons.schedulerdaemon] We have our reactionners:
[2016-10-12 05:49:14 CEST] INFO: [alignak.daemons.schedulerdaemon]  - reactionner-master 
[2016-10-12 05:49:14 CEST] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2016-10-12 05:49:14 CEST] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2016-10-12 05:49:14 CEST] CRITICAL: [alignak.daemon] If you think this is a bug, create a new ticket including details mentioned in the README
[2016-10-12 05:49:14 CEST] CRITICAL: [alignak.daemon] -----
[2016-10-12 05:49:14 CEST] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/schedulerdaemon.py", line 374, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 358, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/schedulerdaemon.py", line 218, in do_loop_turn
    self.setup_new_conf()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/schedulerdaemon.py", line 264, in setup_new_conf
    for sat_id in satellites[sat_type]:
KeyError: 'brokers'
```

```
[2016-10-12 05:16:43 CEST] INFO: [alignak.daemons.brokerdaemon] We have our schedulers: {} 
[2016-10-12 05:16:43 CEST] INFO: [alignak.daemons.brokerdaemon] We have our arbiters: {} 
[2016-10-12 05:16:43 CEST] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2016-10-12 05:16:43 CEST] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2016-10-12 05:16:43 CEST] CRITICAL: [alignak.daemon] If you think this is a bug, create a new ticket including details mentioned in the README
[2016-10-12 05:16:43 CEST] CRITICAL: [alignak.daemon] -----
[2016-10-12 05:16:43 CEST] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/brokerdaemon.py", line 868, in main
    self.setup_new_conf()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/brokerdaemon.py", line 546, in setup_new_conf
    for pol_id in conf['pollers']:
KeyError: 'pollers'
```

**Comment by ddurieux** [comment]
The code is correct, seems like you load the dispatcher of few days ago (before modifications).
Are you sure your Alignak installation is OK ?

**Comment by mohierf** [comment]
I am quite sure my code is ok ... let's keep this issue tracking and I will inform if I still have this problem

**Comment by mohierf** [comment]
Closing. Problem seems due to several arbiter instances running simultaneously
