### ISSUE TITLE
Scheduler exception

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#458]
In a multi-realm configuration (All, with sub-realms Nprth and South), the South realm includes two hosts. The South scheduler raises an exception:

```
[2016-10-13 07:10:41 CEST] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2016-10-13 07:10:44 CEST] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2016-10-13 07:10:44 CEST] CRITICAL: [alignak.daemon] If you think this is a bug, create a new ticket including details mentioned in the README
[2016-10-13 07:10:44 CEST] CRITICAL: [alignak.daemon] -----
[2016-10-13 07:10:44 CEST] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/schedulerdaemon.py", line 372, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 358, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/schedulerdaemon.py", line 214, in do_loop_turn
    self.wait_for_initial_conf()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 1101, in wait_for_initial_conf
    _ = self.handle_requests(timeout)
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 1037, in handle_requests
    tcdiff = self.check_for_system_time_change()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 1068, in check_for_system_time_change
    self.sched.timeperiods)  # pylint: disable=E1101
AttributeError: 'Scheduler' object has no attribute 'timeperiods'
```

**Comment by Seb-Solon** [comment]
This sched is badly init or had a very bad config. timeperiod are given by the arbiter in the config.

**Comment by mohierf** [comment]
This problem was related to a bad configuration
