### ISSUE TITLE
BP rule make the scheduler crash

### ISSUE THREAD

**Issue by fpeyre** [Alignak-monitoring/alignak#465]
Usecase:
Create the following configuration:

```
define host{
        use                     generic-host
        contact_groups          admins
        host_name               localhost
        address                 localhost
        }

define host{
        use                     generic-host
        contact_groups          admins
        host_name               localhost2
        address                 localhost
        }
define host{
        use                     generic-host
        contact_groups          admins
        host_name               BP
        address                 localhost
        check_command          bp_rule!localhost | localhost2
        }

```

The scheduler crashed with the following log : 
```
[2016-10-14 19:16:13 UTC] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2016-10-14 19:16:13 UTC] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2016-10-14 19:16:13 UTC] CRITICAL: [alignak.daemon] If you think this is a bug, create a new ticket including details mentioned in the README
[2016-10-14 19:16:13 UTC] CRITICAL: [alignak.daemon] -----
[2016-10-14 19:16:13 UTC] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/schedulerdaemon.py", line 372, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 358, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/schedulerdaemon.py", line 218, in do_loop_turn
    self.setup_new_conf()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/schedulerdaemon.py", line 243, in setup_new_conf
    conf = unserialize(conf_raw)
  File "/usr/local/lib/python2.7/dist-packages/alignak/misc/serialization.py", line 89, in unserialize
    return cls(data['content'], parsing=False)
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/config.py", line 754, in __init__
    setattr(self, strclss, clss(params[strclss], parsing=parsing))
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/item.py", line 752, in __init__
    self.add_item(self.inner_class(item, parsing=parsing))
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/schedulingitem.py", line 468, in __init__
    self.business_rule = DependencyNode(params['business_rule'])
  File "/usr/local/lib/python2.7/dist-packages/alignak/dependencynode.py", line 86, in __init__
    self.sons = [DependencyNode(elem) for elem in params['sons']]
  File "/usr/local/lib/python2.7/dist-packages/alignak/dependencynode.py", line 86, in __init__
    self.sons = [DependencyNode(elem) for elem in params['sons']]
  File "/usr/local/lib/python2.7/dist-packages/alignak/dependencynode.py", line 85, in __init__
    self.operand = params['operand']
KeyError: 'operand'
```

I think the problem is on the __init__ function of the dependencynode.py. With the pycharm debugger i have seen a params object with operand=host who have sons, but the son doesn't contain the attributes of a DependencyNode object

```
def __init__(self, params=None):

        if params is None:
            self.operand = None
            self.sons = []
            # Of: values are a triple OK,WARN,CRIT
            self.of_values = ('0', '0', '0')
            self.is_of_mul = False
            self.configuration_errors = []
            self.not_value = False
            self.ack_as_ok = False
            self.downtime_as_ok = False
        else:
            self.operand = params['operand']
            self.sons = [DependencyNode(elem) for elem in params['sons']]
            # Of: values are a triple OK,WARN,CRIT
            self.of_values = params['of_values']
            self.is_of_mul = params['is_of_mul']
            self.not_value = params['not_value']
            self.ack_as_ok = params['ack_as_ok']
            self.downtime_as_ok = params['downtime_as_ok']
```

**Comment by fpeyre** [comment]
The problem was resolved in the following commit https://github.com/Alignak-monitoring/alignak/pull/310/commits/7567bb6d800ec3e0acf049d6d6446ae76b91b0d8.
