### ISSUE TITLE
Syntax error in scheduler.py

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#467]
Here: https://github.com/Alignak-monitoring/alignak/blob/develop/alignak/scheduler.py#L589

It should be:

```
                for dependent_checks in chk.depend_on_me:
                    dependent_checks.depend_on.remove(chk.uuid)
                for c_temp in chk.depend_on:
                    c_temp.depend_on_me.remove(chk)
                del self.checks[c_id]  # Final Bye bye ...

```

`c_temp.depend_on_me.` rather than `c_temp.depen_on_me.`

**Comment by ddurieux** [comment]
Yep currently fix it in dependency PR

**Comment by mohierf** [comment]
When running in nosetest, it raises an error in the test *test_clean_checks*:
```
Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/unittest2/case.py", line 67, in testPartExecutor
    yield
  File "/usr/local/lib/python2.7/dist-packages/unittest2/case.py", line 625, in run
    testMethod()
  File "/home/alignak/alignak/test/test_scheduler_clean_queue.py", line 121, in test_clean_checks
    self.scheduler_loop(1, [[host, 0, 'UP'], [svc, 1, 'WARNING']])
  File "/home/alignak/alignak/test/alignak_test.py", line 305, in scheduler_loop
    fun()
  File "/home/alignak/alignak/alignak/scheduler.py", line 589, in clean_queues
    c_temp.depen_on_me.remove(chk)
AttributeError: 'str' object has no attribute 'depen_on_me'
```

**Comment by ddurieux** [comment]
It's fixed
