### ISSUE TITLE
Exception ImportError in some daemons

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#491]
After the merge of some branches (external-commands and coverage-clean) in develop, we get:
```
root@alignakfromscratch:~/git/alignak # alignak-broker -c /usr/local/etc/alignak/arbiter/realms/North/daemons/brokerd-north.ini
Traceback (most recent call last):
  File "/usr/local/bin/alignak-broker", line 6, in <module>
    from alignak.bin.alignak_broker import main
  File "/root/git/alignak/alignak/bin/alignak_broker.py", line 58, in <module>
    from alignak.daemons.brokerdaemon import Broker
  File "/root/git/alignak/alignak/daemons/brokerdaemon.py", line 74, in <module>
    from alignak.external_command import ExternalCommand
  File "/root/git/alignak/alignak/external_command.py", line 71, in <module>
    from alignak.commandcall import CommandCall
  File "/root/git/alignak/alignak/commandcall.py", line 57, in <module>
    from alignak.objects.command import Command
  File "/root/git/alignak/alignak/objects/__init__.py", line 58, in <module>
    from alignak.objects.schedulingitem import SchedulingItem
  File "/root/git/alignak/alignak/objects/schedulingitem.py", line 72, in <module>
    from alignak.objects.commandcallitem import CommandCallItems
  File "/root/git/alignak/alignak/objects/commandcallitem.py", line 25, in <module>
    from alignak.commandcall import CommandCall
ImportError: cannot import name CommandCall
```

**Comment by mohierf** [comment]
This exception is raised because of a cyclic importation due to the `from alignak.commandcall import CommandCall` in *external_commands.py* ... but this import is necessary for the commands that change the check command or event handler ...

**Comment by mohierf** [comment]
Adding some methods to change the `check_command`, `event_handler` and `snapshot_command` of an host/service will fix the problem of importing CommandCall in the external_commands module ...
