### ISSUE TITLE
CommandCall serialize error

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#615]
Exception when reactionner tries to serialize its results

It seems that the `command_call` property of the notification is a string and, thus, it has no serialize method!

Reactionner log
```
[2016-11-21 05:14:18 UTC] INFO: [alignak.satellite] [reactionner-master] Allocating new fork Worker: 83b0fc8abbc5442887c011c562748995
[2016-11-21 05:17:18 UTC] ERROR: [alignak.satellite] Unhandled exception trying to send results to scheduler scheduler-master: 'dict' object has no attribute 'serialize'
Traceback (most recent call last):
  File "/root/git/alignak/alignak/satellite.py", line 376, in do_manage_returns
    {'results': results.values()})
  File "/root/git/alignak/alignak/http/client.py", line 181, in post
    args[key] = serialize(value, True)
  File "/root/git/alignak/alignak/misc/serialization.py", line 56, in serialize
    o_dict = [serialize(item, True) for item in obj]
  File "/root/git/alignak/alignak/misc/serialization.py", line 47, in serialize
    o_dict['content'] = obj.serialize()
  File "/root/git/alignak/alignak/notification.py", line 191, in serialize
    res['command_call'] = res['command_call'].serialize()
AttributeError: 'dict' object has no attribute 'serialize'

```

**Comment by mohierf** [comment]
The `command_call` property contains and *uuid* when the reactionner sends back its results:
```
[2016-11-21 06:16:06 UTC] WARNING: [alignak.notification] Notification serialize: command_call: {'uuid': u'7aa2fc94ff904d7898036a86c89b0af9'}
```
