### ISSUE TITLE
No pollers in the broker configuration

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#658]
Error log in the broker when receiving its configuration:
```
[2016-12-21 18:46:51 CET] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2016-12-21 18:46:51 CET] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2016-12-21 18:46:51 CET] CRITICAL: [alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configuration, ...
[2016-12-21 18:46:51 CET] CRITICAL: [alignak.daemon] -----
[2016-12-21 18:46:51 CET] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/home/alignak/alignak/alignak/daemons/brokerdaemon.py", line 886, in main
    self.setup_new_conf()
  File "/home/alignak/alignak/alignak/daemons/brokerdaemon.py", line 561, in setup_new_conf
    logger.info("[%s] pollers: %s", self.name, conf['pollers'])
KeyError: 'pollers'
```

It seems that sometimes the broker do not receive any poller configuration!

I got this with a test configuration with spare daemons

**Comment by Seb-Solon** [comment]
Does that occurs only on spare or all cases?

**Comment by mohierf** [comment]
AFAIR, only for spare.
