### ISSUE TITLE
Scheduler exception - impacts

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#675]
During my tests with the demo configuration the scheduler always raises this exception:
```
[2017-01-06 13:39:42 CET] WARNING: [alignak.scheduler] The notification command '/usr/local/var/libexec/alignak/notify_by_slack.py -n host -c "PROBLEM,,always_down,,192.168.0.1,,Fri 06 Jan 13:39:38 CET 2017" -o "DOWN,,412140h 39m 38s" -w -u "http://localhost:7767" -K xoxp-18492972628-18498603810-18592116407-3d53165df6 -T "Alignak main" -F Alignak -I ":interrobang:"' raised an error (exit code=1): '2017-01-06 13:39:41,751:ERROR: Slack API problem: token_revoked'
[2017-01-06 13:40:03 CET] WARNING: [alignak.scheduler] The notification command '/usr/local/var/libexec/alignak/notify_by_slack.py -n host -c "PROBLEM,,alignak_glpi,,176.31.224.51,,Fri 06 Jan 13:39:59 CET 2017" -o "DOWN,,412140h 39m 59s" -w -u "http://localhost:7767" -K xoxp-18492972628-18498603810-18592116407-3d53165df6 -T "Alignak main" -F Alignak -I ":interrobang:"' raised an error (exit code=1): '2017-01-06 13:40:03,590:ERROR: Slack API problem: token_revoked'
[2017-01-06 13:40:23 CET] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2017-01-06 13:40:23 CET] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2017-01-06 13:40:23 CET] CRITICAL: [alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configuration, ...
[2017-01-06 13:40:23 CET] CRITICAL: [alignak.daemon] -----
[2017-01-06 13:40:23 CET] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/schedulerdaemon.py", line 394, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 376, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/schedulerdaemon.py", line 224, in do_loop_turn
    self.sched.run()
  File "/usr/local/lib/python2.7/dist-packages/alignak/scheduler.py", line 2178, in run
    fun()
  File "/usr/local/lib/python2.7/dist-packages/alignak/scheduler.py", line 1652, in consume_results
    self.downtimes, self.comments)
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/schedulingitem.py", line 1800, in consume_result
    self.set_myself_as_problem(hosts, services, timeperiods, bi_modulations)
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/schedulingitem.py", line 737, in set_myself_as_problem
    impact = services[impact_id]
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/item.py", line 985, in __getitem__
    return self.items[key] if key else None
KeyError: u'0f7eb1f6be3f45eda20f692a6da43a25'

```

**Comment by mohierf** [comment]
The problem is because of a missing service in the provided services list. 

The configuration on which this occured is the one existing in the alignak-demo repository.

**Comment by ddurieux** [comment]
I think it's a problem before I modify the retention
