### ISSUE TITLE
Scheduler exception - dependencies checks

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#690]
```
[2017-01-14 07:04:17 CET] WARNING: [alignak.objects.schedulingitem] Problem with my impacts: <Host host_name=u'lachassagne' name=u'' use=[] />
[2017-01-14 07:04:37 CET] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2017-01-14 07:04:37 CET] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2017-01-14 07:04:37 CET] CRITICAL: [alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configuration, ...
[2017-01-14 07:04:37 CET] CRITICAL: [alignak.daemon] -----
[2017-01-14 07:04:37 CET] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/root/git/alignak/alignak/daemons/schedulerdaemon.py", line 394, in main
    self.do_mainloop()
  File "/root/git/alignak/alignak/daemon.py", line 372, in do_mainloop
    self.do_loop_turn()
  File "/root/git/alignak/alignak/daemons/schedulerdaemon.py", line 224, in do_loop_turn
    self.sched.run()
  File "/root/git/alignak/alignak/scheduler.py", line 2195, in run
    fun()
  File "/root/git/alignak/alignak/scheduler.py", line 1661, in consume_results
    self.downtimes, self.comments)
  File "/root/git/alignak/alignak/objects/schedulingitem.py", line 1571, in consume_result
    checks)
  File "/root/git/alignak/alignak/objects/schedulingitem.py", line 1134, in raise_dependencies_check
    checks[check_uuid].depend_on_me.append(ref_check)
KeyError: '85a10cc48774438b9c8d883a4b99923a'


```

**Comment by ddurieux** [comment]
duplicate #706
