### ISSUE TITLE
Scheduler exceptions - retention comments exception

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#694]
Exceptions in the scheduler log file:

```
[2017-01-14 13:43:27 CET] INFO: [alignak.http.scheduler_interface] A new broker just connected : broker-master
[2017-01-14 13:43:27 CET] INFO: [alignak.scheduler] [scheduler-master] Created 2648 initial Broks for broker broker-master
[2017-01-14 13:43:29 CET] ERROR: [alignak.scheduler] Downtime to delete: {'comment': u'Schedule downtime by admin, from Alignak-app', 'entry_time': 1481453176, 'activate_me':
[], 'uuid': u'bd1effe6d7f247adab822c0f23108ca7', 'author': u'admin', 'start_time': 1481453169, 'comment_id': u'f92232d4464346adb8c4920d847fd2e6', 'trigger_id': u'0', 'has_been
_triggered': False, 'real_end_time': 1481539569, 'end_time': 1481539569, 'duration': 86400, 'ref_type': u'host', 'fixed': True, 'ref': u'cec6aa8afc234f309a4d2477e3e9c82b', 'ca
n_be_deleted': True, 'is_in_effect': False}
```
```
[2017-01-14 14:44:03 CET] ERROR: [alignak.scheduler] The instance backend_scheduler raise an exception u'f92232d4464346adb8c4920d847fd2e6'.I disable it and set it to restart i
t later
[2017-01-14 14:44:03 CET] ERROR: [alignak.scheduler] Exception trace follows: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 552, in hook_point
    fun(self)
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend/scheduler/module.py", line 157, in hook_save_retention
    data_to_save = scheduler.get_retention_data()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 1334, in get_retention_data
    comments.append(self.comments[comment_uuid].serialize())
KeyError: u'f92232d4464346adb8c4920d847fd2e6'
```
```
[2017-01-14 15:44:38 CET] ERROR: [alignak.scheduler] The instance backend_scheduler raise an exception u'f92232d4464346adb8c4920d847fd2e6'.I disable it and set it to restart i
t later
[2017-01-14 15:44:38 CET] ERROR: [alignak.scheduler] Exception trace follows: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 552, in hook_point
    fun(self)
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend/scheduler/module.py", line 157, in hook_save_retention
    data_to_save = scheduler.get_retention_data()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 1334, in get_retention_data
    comments.append(self.comments[comment_uuid].serialize())
KeyError: u'f92232d4464346adb8c4920d847fd2e6'

```

**Comment by mohierf** [comment]
Still got one today, but probably more concerned is the backend module:
```
==> /usr/local/var/log/alignak/schedulerd.log <==
[2017-01-21 11:57:31 CET] ERROR: [alignak.scheduler] The instance backend_scheduler raise an exception u'800e22841b29416598467e9ba642c176'.I disable it and set it to restart it later
[2017-01-21 11:57:31 CET] ERROR: [alignak.scheduler] Exception trace follows: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 567, in hook_point
    fun(self)
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend/scheduler/module.py", line 157, in hook_save_retention
    data_to_save = scheduler.get_retention_data()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 1412, in get_retention_data
    self.comments[downtime_ser['comment_id']].serialize()
KeyError: u'800e22841b29416598467e9ba642c176'

```
