### ISSUE TITLE
CherryPy version >8.9 breaks Alignak

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#703]
The recent CherryPy versions (>=9.0) are breaking Alignak:
```
>>> from alignak.daemons.arbiterdaemon import Arbiter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/arbiterdaemon.py", line 74, in <module>
    from alignak.daemon import Daemon
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 131, in <module>
    from alignak.http.daemon import HTTPDaemon, InvalidWorkDir, PortNotFree
  File "/usr/local/lib/python2.7/dist-packages/alignak/http/daemon.py", line 31, in <module>
    from cherrypy.wsgiserver import CherryPyWSGIServer
ImportError: No module named wsgiserver
```

Setting `CherryPy<9.0.0` as a requirement is mandatory!

----
This issue is simply to keep tracking this problem which was solved with #700

**Comment by efficks** [comment]
Hi, @mohierf 
CHerryPi project seems to have extract their wsgiserver module and move it in a standalone project named cheroot.
It seems we can directely replace reference to 'wsgiserver' to 'cheroot.server'.

See : 
https://github.com/cherrypy/cherrypy/issues/1481

**Comment by mohierf** [comment]
Thanks @efficks for reporting. I will open an issue to update CherryPy version.
