### ISSUE TITLE
Scheduler exception: dependencies

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#706]
```
[2017-01-20 23:43:41 CET] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2017-01-20 23:43:41 CET] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2017-01-20 23:43:41 CET] CRITICAL: [alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configuration, ...
[2017-01-20 23:43:41 CET] CRITICAL: [alignak.daemon] -----
[2017-01-20 23:43:41 CET] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 394, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 376, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 224, in do_loop_turn
    self.sched.run()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 2225, in run
    fun()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 1686, in consume_results
    self.downtimes, self.comments)
  File "/usr/local/lib/python2.7/site-packages/alignak/objects/schedulingitem.py", line 1569, in consume_result
    checks)
  File "/usr/local/lib/python2.7/site-packages/alignak/objects/schedulingitem.py", line 1134, in raise_dependencies_check
    checks[check_uuid].depend_on_me.append(ref_check)
KeyError: 'fa719e5632b1475ea6ae52ee5786b6a3'

```

**Comment by ddurieux** [comment]
I think the retention is the problem, but with tests added, it's not it, I continue searching the problem...

**Comment by ddurieux** [comment]
Ok, I think we need reset all checks of scheduler when restore the retention, I check that

**Comment by mohierf** [comment]
Why closing this now...? With the label `not-reproduced` we keep this open and we will close in some days/weeks/months if the problem is not reproduced anymore

**Comment by mohierf** [comment]
No more observed since a while ... I am closing this issue
