### ISSUE TITLE
External commands with special characters break the receiver

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#710]
```
[2017-01-25 15:41:14 UTC] WARNING: [alignak.daemons.receiverdaemon] manage_returns exception:: <class 'alignak.http.client.HTTPException'>,\
Request error to http://127.0.0.1:7768/run_external_commands: HTTP POST not OK: 500 ; text=u'<!DOCTYPE html PUBLIC\n"-//W3C//DTD XHTML 1.0 \
Transitional//EN"\n"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html>\n<head>\n    <meta http-equiv="Content-Type" \
content="text/html; charset=utf-8"></meta>\n    <title>500 Internal Server Error</title>\n    <style type="text/css">\n    #powered_by {\n    
    margin-top: 20px;\n        border-top: 2px solid black;\n        font-style: italic;\n    }\n\n    #traceback {\n        color: red;\n    }\n 
	</style>\n</head>\n    <body>\n        <h2>500 Internal Server Error</h2>\n        <p>The server encountered an unexpected condition which prevented it 
	from fulfilling the request.</p>\n        <pre id="traceback">Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/cherrypy
	/_cprequest.py", line 670, in respond\n    response.body = self.handler()\n  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", l
	ne 220, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 61, 
	in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py",
	line 60, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/alignak/http/scheduler_interface.py",
	line 196, in run_external_commands\n    self.app.sched.run_external_commands(commands[\'cmds\'])\n  
	File "/usr/local/lib/python2.7/dist-packages/alignak/scheduler.py", line 404, in run_external_commands\n  
	self.run_external_command(command)\n  File "/usr/local/lib/python2.7/dist-packages/alignak/scheduler.py", line 416, 
	in run_external_command\n    self.external_commands_manager.resolve_command(ext_cmd)\n  File "/usr/local/lib/python2.7/dist-packages/alignak/external_command.py",
	line 565, in resolve_command\n    getattr(self, c_name)(*args)\n  File "/usr/local/lib/python2.7/dist-packages/alignak/external_command.py", 
	line 3066, in process_service_check_result\n    chk.get_outputs(plugin_output, service.max_plugins_output_length)\n 
	File "/usr/local/lib/python2.7/dist-packages/alignak/action.py", line 241, in get_outputs\n    self.output = self.output.decode(\'utf8\', \'ignore\')\n  
	File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode\n    return codecs.utf_8_decode(input, errors, True)\nUnicodeEncodeError: 
	\'ascii\' codec can\'t encode character u\'\\xe4\' in position 121: ordinal not in range(128)\n</pre>\n    <div id="powered_by">\n    
	<span>\n        Powered by <a href="http://www.cherrypy.org">CherryPy 8.9.1</a>\n      </span>\n    </div>\n    </body>\n</html>\n' 
	
[2017-01-25 15:41:14 UTC] WARNING: [alignak.daemons.receiverdaemon] Connection problem to the scheduler {'wait_homerun': {}, 'external_commands'
: [<alignak.external_command.ExternalCommand instance at 0x7f3f343e68c0>, <alignak.external_command.ExternalCommand instance at 0x7f3f376027a0>,
 <alignak.external_command.ExternalCommand instance at 0x7f3f343c4bd8>, <alignak.external_command.ExternalCommand instance at 0x7f3f376279e0>, 
 <alignak.external_command.ExternalCommand instance at 0x7f3f376025a8>, <alignak.external_command.ExternalCommand instance at 0x7f3f343e6d88>, 
 <alignak.external_command.ExternalCommand instance at 0x7f3f343d91b8>, <alignak.external_command.ExternalCommand instance at 0x7f3f343d9290>, 
 <alignak.external_command.ExternalCommand instance at 0x7f3f37627ea8>, <alignak.external_command.ExternalCommand instance at 0x7f3f47eb0290>, 
 <alignak.external_command.ExternalCommand instance at 0x7f3f34383710>, <alignak.external_command.ExternalCommand instance at 0x7f3f3438cef0>,
 <alignak.external_command.ExternalCommand instance at 0x7f3f3761d248>, <alignak.external_command.ExternalCommand instance at 0x7f3f34374488>,
 <alignak.external_command.ExternalCommand instance at 0x7f3f47de76c8>], u'data_timeout': 120, u'name': u'scheduler-master', u'hard_ssl_name_check': 
 False, 'uri': u'http://127.0.0.1:7768/', 'actions': {}, u'instance_id': u'4270829279ff4c628bea863ec509d9d3',
 u'hosts': [u' xyz - my hosts u'test.host.A'], 'running_id': 1485358661.3921285, u'timeout': 3, u'address': u'127.0.0.1', u'active': True, u'use_ssl': 
 False, u'push_flavor': 845923, u'port': 7768, 'con': <alignak.http.client.HTTPClient object at 0x7f3f37620e90>}: Request error to 
 http://127.0.0.1:7768/run_external_commands: HTTP POST not OK: 500 ; text=u'<!DOCTYPE html PUBLIC\n"-//W3C//DTD XHTML 1.0 
 Transitional//EN"\n"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html>\n<head>\n    <meta http-equiv="Content-Type" content="text/html; 
 charset=utf-8"></meta>\n    <title>500 Internal Server Error</title>\n    <style type="text/css">\n    #powered_by {\n        margin-top: 20px;\n      
 border-top: 2px solid black;\n        font-style: italic;\n    }\n\n    #traceback {\n        color: red;\n    }\n    </style>\n</head>\n    <body>\n   
 <h2>500 Internal Server Error</h2>\n        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>\n     
 <pre id="traceback">Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond\n 
 response.body = self.handler()\n  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__\n   
 self.body = self.oldhandler(*args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 61, in 
 json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", 
 line 60, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/alignak/http/scheduler_interface.py", 
 line 196, in run_external_commands\n    self.app.sched.run_external_commands(commands[\'cmds\'])\n  
 File "/usr/local/lib/python2.7/dist-packages/alignak/scheduler.py", line 404, in run_external_commands\n 
 self.run_external_command(command)\n  File "/usr/local/lib/python2.7/dist-packages/alignak/scheduler.py", line 416,
 in run_external_command\n    self.external_commands_manager.resolve_command(ext_cmd)\n  File "/usr/local/lib/python2.7/dist-packages/alignak/external_command.py",
 line 565, in resolve_command\n    getattr(self, c_name)(*args)\n  File "/usr/local/lib/python2.7/dist-packages/alignak/external_command.py", 
 line 3066, in process_service_check_result\n    chk.get_outputs(plugin_output, service.max_plugins_output_length)\n 
 File "/usr/local/lib/python2.7/dist-packages/alignak/action.py", line 241, in get_outputs\n    self.output = self.output.decode(\'utf8\', \'ignore\')\n 
 File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode\n    return codecs.utf_8_decode(input, errors, 
 True)\nUnicodeEncodeError: \'ascii\' codec can\'t encode character u\'\\xe4\' in position 121: ordinal not in range(128)\n</pre>\n 
 <div id="powered_by">\n      <span>\n        Powered by <a href="http://www.cherrypy.org">CherryPy 8.9.1</a>\n      </span>\n    </div>\n  
 </body>\n</html>\n'
[2017-01-25 15:41:14 UTC] INFO: [alignak.satellite] [receiver-master] Init connection with scheduler-master at http://127.0.0.1:7768/ (3s,120s)
[2017-01-25 15:41:14 UTC] INFO: [alignak.satellite] [receiver-master] Connection OK with scheduler scheduler-master
```

**Comment by spea1** [comment]
Possible source of error:

```
...
[1485512308] INFO: EXTERNAL COMMAND: [1485509859] PROCESS_SERVICE_CHECK_RESULT;MyHOST;nsca_disk;3;Filter processing failed: Failed to get size for \\?\Volume{aaae5bc1-0000-0000-0000-100000000000}\: 1005: Auf dem DatentrÃ¤ger befindet sich kein erkanntes Dateisystem.
Stellen Sie sicher, dass alle benötigten Dateisystemtreiber geladen sind und dass der Datenträger nicht beschädigt ist.
: 0 <= convert(0)
[1485512310] INFO: EXTERNAL COMMAND: [1485509859] PROCESS_SERVICE_CHECK_RESULT;MyHOST;nsca_disk;3;Filter processing failed: Failed to get size for \\?\Volume{aaae5bc1-0000-0000-0000-100000000000}\: 1005: Auf dem DatentrÃ¤ger befindet sich kein erkanntes Dateisystem.
Stellen Sie sicher, dass alle benötigten Dateisystemtreiber geladen sind und dass der Datenträger nicht beschädigt ist.
: 0 <= convert(0)
[1485512316] INFO: EXTERNAL COMMAND: [1485509859] PROCESS_SERVICE_CHECK_RESULT;MyHOST;nsca_disk;3;Filter processing failed: Failed to get size for \\?\Volume{aaae5bc1-0000-0000-0000-100000000000}\: 1005: Auf dem DatentrÃ¤ger befindet sich kein erkanntes Dateisystem.
Stellen Sie sicher, dass alle benötigten Dateisystemtreiber geladen sind und dass der Datenträger nicht beschädigt ist.
: 0 <= convert(0)
...
```

**Comment by mohierf** [comment]
This command:
```
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: 7d68a7bd-6a43-a233-62df-77bb0ba93c54" -d '{
	"command": "PROCESS_SERVICE_CHECK_RESULT",
	"element": "always_down;NetworkUsage",
	"parameters": "nsca_disk;3;Filter processing failed: Failed to get size for \\\\?\\Volume{aaae5bc1-0000-0000-0000-100000000000}\\: 1005: Auf dem Datenträger befindet sich kein erkanntes Dateisystem. Stellen Sie sicher, dass alle benötigten Dateisystemtreiber geladen sind und dass der Datenträger nicht beschädigt ist. : 0 <= convert(0)"
}' "http://demo.alignak.net:8888/command"
```
using the Alignak WS also breaks the Alignak receiver:
```
[2017-01-28 12:15:13 CET] WARNING: [alignak.daemons.receiverdaemon] manage_returns exception:: <class 'alignak.http.client.HTTPException'>,Request error to http://127.0.0.1:7768/run_external_commands: HTTP POST not OK: 500 ; text=u'<!DOCTYPE html PUBLIC\n"-//W3C//DTD XHTML 1.0 Transitional//EN"\n"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html>\n<head>\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>\n    <title>500 Internal Server Error</title>\n    <style type="text/css">\n    #powered_by {\n        margin-top: 20px;\n        border-top: 2px solid black;\n        font-style: italic;\n    }\n\n    #traceback {\n        color: red;\n    }\n    </style>\n</head>\n    <body>\n        <h2>500 Internal Server Error</h2>\n        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>\n        <pre id="traceback">Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond\n    response.body = self.handler()\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 220, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/lib/jsontools.py", line 61, in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File "/usr/local/lib/python2.7/site-packages/alignak/http/scheduler_interface.py", line 196, in run_external_commands\n    self.app.sched.run_external_commands(commands[\'cmds\'])\n  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 404, in run_external_commands\n    self.run_external_command(command)\n  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 416, in run_external_command\n    self.external_commands_manager.resolve_command(ext_cmd)\n  File "/usr/local/lib/python2.7/site-packages/alignak/external_command.py", line 544, in resolve_command\n    res = self.get_command_and_args(command.strip(), excmd)\n  File "/usr/local/lib/python2.7/site-packages/alignak/external_command.py", line 820, in get_command_and_args\n    args.append(to_int(val))\n  File "/usr/local/lib/python2.7/site-packages/alignak/util.py", line 361, in to_int\n    return int(float(val))\nValueError: could not convert string to float: nsca_disk\n</pre>\n    <div id="powered_by">\n      <span>\n        Powered by <a href="http://www.cherrypy.org">CherryPy 8.9.1</a>\n      </span>\n    </div>\n    </body>\n</html>\n'
[2017-01-28 12:15:13 CET] WARNING: [alignak.daemons.receiverdaemon] Connection problem to the scheduler {'wait_homerun': {}, 'external_commands': [<alignak.external_command.ExternalCommand instance at 0x80d43c2d8>], u'data_timeout': 120, u'name': u'scheduler-master', u'hard_ssl_name_check': False, 'uri': u'http://127.0.0.1:7768/', 'actions': {}, u'instance_id': u'b5351bdaf1a84f2198a01b01af3a325c', u'hosts': [u'cogny', u'denice', u'lachassagne', u'always_down', u'localhost', u'new-passive', u'alignak_glpi', u'chazay'], 'running_id': 1485601523.8793025, u'timeout': 3, u'address': u'127.0.0.1', u'active': True, u'use_ssl': False, u'push_flavor': 901168, u'port': 7768, 'con': <alignak.http.client.HTTPClient object at 0x80d41e390>}: Request error to http://127.0.0.1:7768/run_external_commands: HTTP POST not OK: 500 ; text=u'<!DOCTYPE html PUBLIC\n"-//W3C//DTD XHTML 1.0 Transitional//EN"\n"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html>\n<head>\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>\n    <title>500 Internal Server Error</title>\n    <style type="text/css">\n    #powered_by {\n        margin-top: 20px;\n        border-top: 2px solid black;\n        font-style: italic;\n    }\n\n    #traceback {\n        color: red;\n    }\n    </style>\n</head>\n    <body>\n        <h2>500 Internal Server Error</h2>\n        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>\n        <pre id="traceback">Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond\n    response.body = self.handler()\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 220, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/lib/jsontools.py", line 61, in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File "/usr/local/lib/python2.7/site-packages/alignak/http/scheduler_interface.py", line 196, in run_external_commands\n    self.app.sched.run_external_commands(commands[\'cmds\'])\n  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 404, in run_external_commands\n    self.run_external_command(command)\n  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 416, in run_external_command\n    self.external_commands_manager.resolve_command(ext_cmd)\n  File "/usr/local/lib/python2.7/site-packages/alignak/external_command.py", line 544, in resolve_command\n    res = self.get_command_and_args(command.strip(), excmd)\n  File "/usr/local/lib/python2.7/site-packages/alignak/external_command.py", line 820, in get_command_and_args\n    args.append(to_int(val))\n  File "/usr/local/lib/python2.7/site-packages/alignak/util.py", line 361, in to_int\n    return int(float(val))\nValueError: could not convert string to float: nsca_disk\n</pre>\n    <div id="powered_by">\n      <span>\n        Powered by <a href="http://www.cherrypy.org">CherryPy 8.9.1</a>\n      </span>\n    </div>\n    </body>\n</html>\n'

```

**Comment by mohierf** [comment]
To help decoding the error message :wink: the error happens in the *action.py* module: 
```
        # First line before | is output, strip it
        self.output = elts_line1[0].strip().replace('___PROTECT_PIPE___', '|')
        self.output = self.output.decode('utf8', 'ignore')
```

Trying to decode an already utf-8 encoded string raises a `UnicodeEncodeError` exception ...
