### ISSUE TITLE
Error comment in end of downtime

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#746]
```
[2017-02-28 22:50:00 CET] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2017-02-28 22:50:00 CET] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2017-02-28 22:50:00 CET] CRITICAL: [alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configuration, ...
[2017-02-28 22:50:00 CET] CRITICAL: [alignak.daemon] -----
[2017-02-28 22:50:00 CET] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 394, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 376, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 224, in do_loop_turn
    self.sched.run()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 2096, in run
    fun()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 1697, in update_downtimes_and_comments
    broks.extend(downtime.exit(self.timeperiods, self.hosts, self.services))
  File "/usr/local/lib/python2.7/site-packages/alignak/downtime.py", line 255, in exit
    item.del_comment(self.comment_id)
  File "/usr/local/lib/python2.7/site-packages/alignak/objects/item.py", line 532, in del_comment
    del self.comments[comment_id]
TypeError: unhashable type: 'dict'
```

**Comment by mohierf** [comment]
Same error on the demo server:
```
[2017-03-01 17:20:15 CET] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2017-03-01 17:20:15 CET] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2017-03-01 17:20:15 CET] CRITICAL: [alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configuration, ...
[2017-03-01 17:20:15 CET] CRITICAL: [alignak.daemon] -----
[2017-03-01 17:20:15 CET] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 394, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 376, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 224, in do_loop_turn
    self.sched.run()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 2096, in run
    fun()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 1697, in update_downtimes_and_comments
    broks.extend(downtime.exit(self.timeperiods, self.hosts, self.services))
  File "/usr/local/lib/python2.7/site-packages/alignak/downtime.py", line 255, in exit
    item.del_comment(self.comment_id)
  File "/usr/local/lib/python2.7/site-packages/alignak/objects/item.py", line 532, in del_comment
    del self.comments[comment_id]
TypeError: unhashable type: 'dict'

```

**Comment by ddurieux** [comment]
It's the error of the demo :p 
Seems it's a problem with retention, I think with old retention (before my last modifications) because the `comment_id` property is a dict (of the comment) instead a uuid
