### ISSUE TITLE
Scheduler exception, again ...

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#751]
```
[2017-03-07 13:44:43 CET] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2017-03-07 13:44:43 CET] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2017-03-07 13:44:43 CET] CRITICAL: [alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configuration, ...
[2017-03-07 13:44:43 CET] CRITICAL: [alignak.daemon] -----
[2017-03-07 13:44:43 CET] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 394, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 376, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 224, in do_loop_turn
    self.sched.run()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 2232, in run
    fun()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 1693, in consume_results
    self.downtimes, self.comments)
TypeError: consume_result() takes exactly 12 arguments (14 given)
```

**Comment by ddurieux** [comment]
All consume_result() calls in scheduler.py has 11 arguments, so perhaps it's an old piece of code
