### ISSUE TITLE
Exception for scheduler retention on configuration reload

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#771]
When reloading the configuration, some exceptions in the scheduler:
```
[2017-04-05 06:09:17 CEST] INFO: [alignak.scheduler] [scheduler-north] Created 403 initial Broks for broker broker-master
[2017-04-05 06:13:56 CEST] INFO: [alignak.module.backend_scheduler] 4 hosts saved in retention
[2017-04-05 06:13:57 CEST] INFO: [alignak.http.scheduler_interface] A new broker just connected : broker-north
[2017-04-05 06:13:57 CEST] INFO: [alignak.scheduler] [scheduler-north] Created 204 initial Broks for broker broker-north
[2017-04-05 06:13:58 CEST] INFO: [alignak.module.backend_scheduler] 74 services saved in retention
[2017-04-05 06:13:58 CEST] INFO: [alignak.daemon] Waiting for initial configuration
[2017-04-05 06:13:58 CEST] INFO: [alignak.daemons.schedulerdaemon] New configuration received
[2017-04-05 06:13:58 CEST] WARNING: [alignak.daemons.schedulerdaemon] Sending us a configuration 240828
[2017-04-05 06:13:58 CEST] INFO: [alignak.module.backend_scheduler] 4 hosts saved in retention
[2017-04-05 06:13:59 CEST] ERROR: [alignak.module.backend_scheduler] Backend exception: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> /
 404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/retentionservice/58e46f05a032849a90415ea5
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend/scheduler/module.py", line 199, in hook_save_retention
    headers=delheaders)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 698, in delete
    raise BackendException(1003, "Backend HTTPError: %s / %s" % (type(e), str(e)))
BackendException: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/retentions
ervice/58e46f05a032849a90415ea5
[2017-04-05 06:13:59 CEST] ERROR: [alignak.module.backend_scheduler] Backend exception: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> /
 404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/retentionservice/58e46f05a032849a9241d9bf
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend/scheduler/module.py", line 199, in hook_save_retention
    headers=delheaders)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 698, in delete
    raise BackendException(1003, "Backend HTTPError: %s / %s" % (type(e), str(e)))
BackendException: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/retentions
ervice/58e46f05a032849a9241d9bf
[2017-04-05 06:13:59 CEST] ERROR: [alignak.module.backend_scheduler] Backend exception: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> /
 404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/retentionservice/58e46f05a032849a90415ea6
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend/scheduler/module.py", line 199, in hook_save_retention
    headers=delheaders)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 698, in delete
    raise BackendException(1003, "Backend HTTPError: %s / %s" % (type(e), str(e)))
BackendException: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/retentions
ervice/58e46f05a032849a90415ea6
[2017-04-05 06:13:59 CEST] ERROR: [alignak.module.backend_scheduler] Backend exception: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> /
 404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/retentionservice/58e46f06a032849a90415ea7
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend/scheduler/module.py", line 199, in hook_save_retention
    headers=delheaders)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 698, in delete
    raise BackendException(1003, "Backend HTTPError: %s / %s" % (type(e), str(e)))
BackendException: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/retentions
ervice/58e46f06a032849a90415ea7
[2017-04-05 06:13:59 CEST] ERROR: [alignak.module.backend_scheduler] Backend exception: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> /
 404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/retentionservice/58e46f06a032849a9241d9c0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend/scheduler/module.py", line 199, in hook_save_retention
    headers=delheaders)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 698, in delete
    raise BackendException(1003, "Backend HTTPError: %s / %s" % (type(e), str(e)))
BackendException: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/retentions
ervice/58e46f06a032849a9241d9c0
[2017-04-05 06:13:59 CEST] ERROR: [alignak.module.backend_scheduler] Backend exception: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> /
 404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/retentionservice/58e46f06a032849a90415eb3
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend/scheduler/module.py", line 199, in hook_save_retention
    headers=delheaders)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 698, in delete
    raise BackendException(1003, "Backend HTTPError: %s / %s" % (type(e), str(e)))
BackendException: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/retentions
ervice/58e46f06a032849a90415eb3
[2017-04-05 06:14:00 CEST] INFO: [alignak.module.backend_scheduler] 74 services saved in retention
[2017-04-05 06:14:00 CEST] INFO: [alignak.stats] Sending scheduler/scheduler-north daemon statistics to: localhost:8125, prefix: alignak-demo
[2017-04-05 06:14:00 CEST] INFO: [alignak.stats] Trying to contact StatsD server...
[2017-04-05 06:14:00 CEST] INFO: [alignak.stats] StatsD server contacted
[2017-04-05 06:14:00 CEST] INFO: [alignak.daemons.schedulerdaemon] We have our pollers:
[2017-04-05 06:14:00 CEST] INFO: [alignak.daemons.schedulerdaemon]  - poller-north
[2017-04-05 06:14:00 CEST] INFO: [alignak.daemons.schedulerdaemon] We have our reactionners:
[2017-04-05 06:14:00 CEST] INFO: [alignak.daemons.schedulerdaemon] We have our brokers:
[2017-04-05 06:14:00 CEST] INFO: [alignak.daemons.schedulerdaemon]  - broker-master
[2017-04-05 06:14:00 CEST] INFO: [alignak.daemons.schedulerdaemon]  - broker-north
[2017-04-05 06:14:00 CEST] INFO: [alignak.daemon] Loading modules...
[2017-04-05 06:14:00 CEST] INFO: [alignak.modulesmanager] Importing Python module 'alignak_module_backend.scheduler' for backend_scheduler...
[2017-04-05 06:14:00 CEST] INFO: [alignak.modulesmanager] Module properties: {'daemons': ['scheduler'], 'phases': ['running'], 'type': 'backend_scheduler', 'external': False
}
[2017-04-05 06:14:00 CEST] INFO: [alignak.modulesmanager] Imported 'alignak_module_backend.scheduler' for backend_scheduler
[2017-04-05 06:14:00 CEST] INFO: [alignak.modulesmanager] Loaded Python module 'alignak_module_backend.scheduler' (backend_scheduler)
[2017-04-05 06:14:00 CEST] INFO: [alignak.module.backend_scheduler] Give an instance of alignak_module_backend.scheduler for alias: backend_scheduler
[2017-04-05 06:14:00 CEST] INFO: [alignak.module.backend_scheduler] Number of processes used by backend client: 1
[2017-04-05 06:14:00 CEST] INFO: [alignak.modulesmanager] Trying to initialize module: backend_scheduler
[2017-04-05 06:14:00 CEST] INFO: [alignak.daemon] I correctly loaded my modules: [backend_scheduler]
[2017-04-05 06:14:00 CEST] INFO: [alignak.daemons.schedulerdaemon] Loading configuration.
[2017-04-05 06:14:01 CEST] INFO: [alignak.daemons.schedulerdaemon] New configuration loaded
[2017-04-05 06:14:01 CEST] INFO: [alignak.http.scheduler_interface] A new broker just connected : broker-north
[2017-04-05 06:14:01 CEST] INFO: [alignak.scheduler] [scheduler-north] Created 263 initial Broks for broker broker-north
[2017-04-05 06:14:02 CEST] INFO: [alignak.scheduler] [scheduler-north] First scheduling launched
[2017-04-05 06:14:02 CEST] INFO: [alignak.scheduler] [scheduler-north] First scheduling done
[2017-04-05 06:14:20 CEST] INFO: [alignak.http.scheduler_interface] A new broker just connected : broker-master
[2017-04-05 06:14:20 CEST] INFO: [alignak.scheduler] [scheduler-north] Created 401 initial Broks for broker broker-master

```

**Comment by mohierf** [comment]
Probably this issue is related to the alignak backend module ... I opened it here because it is raised in Alignak log files 😉

**Comment by mohierf** [comment]
Looks fixed as of now
