### ISSUE TITLE
Exception in push_external_commands_to_schedulers function

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#882]
On the load-test-suite branch:

```
[2017-07-30 13:21:52 CEST] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2017-07-30 13:21:52 CEST] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2017-07-30 13:21:52 CEST] CRITICAL: [alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configura
tion, ...
[2017-07-30 13:21:52 CEST] CRITICAL: [alignak.daemon] -----
[2017-07-30 13:21:52 CEST] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 460, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 403, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 425, in do_loop_turn
    self.push_external_commands_to_schedulers()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 364, in push_external_commands_to_schedulers
    "not possible to push external commands.", sched.scheduler_name)
AttributeError: 'dict' object has no attribute 'scheduler_name'

```

**Comment by mohierf** [comment]
What looks strange it that the scheduler object should have a `scheduler_name` property :/p
