### ISSUE TITLE
Receiver exception because of scheduler communication problem

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#887]
We should protect against such exceptions: 
```
[2017-08-05 18:11:32 CEST] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2017-08-05 18:11:32 CEST] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2017-08-05 18:11:32 CEST] CRITICAL: [alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configura
tion, ...
[2017-08-05 18:11:32 CEST] CRITICAL: [alignak.daemon] -----
[2017-08-05 18:11:32 CEST] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 460, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 403, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 425, in do_loop_turn
    self.push_external_commands_to_schedulers()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 375, in push_external_commands_to_schedulers
    logger.warning("[%s] %s", sched.scheduler_name, str(exp))
AttributeError: 'dict' object has no attribute 'scheduler_name'

```

**Comment by mohierf** [comment]
But it is still not the good solution, because:
```
[2017-08-06 19:00:03 CEST] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2017-08-06 19:00:03 CEST] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2017-08-06 19:00:03 CEST] CRITICAL: [alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configura
tion, ...
[2017-08-06 19:00:03 CEST] CRITICAL: [alignak.daemon] -----
[2017-08-06 19:00:03 CEST] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 460, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 403, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 425, in do_loop_turn
    self.push_external_commands_to_schedulers()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 375, in push_external_commands_to_schedulers
    logger.warning("[%s] %s", sched.get_name(), str(exp))
AttributeError: 'dict' object has no attribute 'get_name'
```

**Comment by mohierf** [comment]
It looks like the receiver got its scheduler list but it is not a list of SatelliteLink objects ... hmmm, strange!

**Comment by mohierf** [comment]
Same as #882, closes #882

**Comment by spea1** [comment]
After the update the same Problem

```
# -----------------------------------------------------------------------------
# alignak: develop
Date:   Thu Aug 10 09:22:06 2017 +0200
b858a3aa2dce9a863fe6c2c1c170471bffbdd168
Author: Frédéric MOHIER <frederic.mohier@gmail.com>
```


```
c:\Program Files\NSClient++>cscript.exe //T:30 //NoLogo scripts\lib\wrapper.vbs scripts\check_updates.vbs -warning 0 -critical 0
OK: Number of critical updates not installed: 4 <br />Number of software updates not installed: 0 <br /> Critical updates name: Definitionsupdate für Windows Defender – KB2267602 (Definition 1.249.883.0)+ 2017-08 Kumulatives Update für Windows 10 Version 1703 für x64-basierte Systeme (KB4034674)+ Windows-Tool zum Entfernen bösartiger Software für Windows 8, 8.1, 10 und Windows Server 2012, 2012 R2, 2016 x64 Edition - August 2017 (KB890830)+ 2017-08 Sicherheitsupdate für Adobe Flash Player für Windows 10 Version 1703 für x64-basierte Systeme (KB4034662)+
```

```
[2017-08-10 10:20:05 CEST] INFO: [alignak.module.nsca] Decoded NSCA packet: host/service: test-b/nsca_updates, timestamp: 1502353205, output: OK: Number of critical updates not installed: 4 <br />Number of software updates not installed:0 <br /> Critical updates name: Definitionsupdate f.r Windows Defender - KB2267602 (Definition 1.249.883.0)+ 2017-08 Kumulatives Update f.r Windows 10 Version 1
[2017-08-10 10:20:06 CEST] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2017-08-10 10:20:06 CEST] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2017-08-10 10:20:06 CEST] CRITICAL: [alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configuration, ...
[2017-08-10 10:20:06 CEST] CRITICAL: [alignak.daemon] -----
[2017-08-10 10:20:06 CEST] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/receiverdaemon.py", line 461, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 408, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/receiverdaemon.py", line 425, in do_loop_turn
    self.push_external_commands_to_schedulers()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/receiverdaemon.py", line 385, in push_external_commands_to_schedulers
    "sending external commands: %s", sched.scheduler_name, str(exp))
AttributeError: 'dict' object has no attribute 'scheduler_name'

[2017-08-10 10:20:06 CEST] INFO: [alignak.basemodule] Process for module web-services is now exiting (pid=22863)
[2017-08-10 10:20:06 CEST] INFO: [alignak.module.nsca] Decoded NSCA packet: host/service: test-b/nsca_uptime, timestamp: 1502353206, output: OK: uptime: 15:40h, boot: 2017-08-09 16:39:10 (UTC)|'uptime'=56458s;7200;3600
[2017-08-10 10:20:06 CEST] INFO: [alignak.basemodule] Process for module nsca is now exiting (pid=22910)
```

**Comment by spea1** [comment]
to info:


```
[2017-08-11 09:36:26 CEST] INFO: [alignak.module.nsca] Decoded NSCA packet: host/service: test-b/nsca_disk, timestamp: 1502436986, output: Filter processing failed: Failed to get size for \\?\Volume{aaae5bc1-0000-0000-0000-100000000000}\: 1005: Auf dem Datenträger befindet sich kein erkanntes Dateisystem. Stellen Sie sicher, dass alle benötigten Dateisystemtreiber geladen sind und dass der D
[2017-08-11 09:36:26 CEST] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2017-08-11 09:36:26 CEST] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2017-08-11 09:36:26 CEST] CRITICAL: [alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configuration, ...
[2017-08-11 09:36:26 CEST] CRITICAL: [alignak.daemon] -----
[2017-08-11 09:36:26 CEST] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/receiverdaemon.py", line 461, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 408, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/receiverdaemon.py", line 425, in do_loop_turn
    self.push_external_commands_to_schedulers()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/receiverdaemon.py", line 385, in push_external_commands_to_schedulers
    "sending external commands: %s", sched.scheduler_name, str(exp))
AttributeError: 'dict' object has no attribute 'scheduler_name'

[2017-08-11 09:36:27 CEST] INFO: [alignak.basemodule] Process for module web-services is now exiting (pid=8736)
[2017-08-11 09:36:28 CEST] INFO: [alignak.basemodule] Process for module nsca is now exiting (pid=3866)

```
