### ISSUE TITLE
Exception on module configuration loading

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#890]
As reported by @spea1, exception when restoring configuration from an arbiter module:

```
[2017-08-05 23:45:18 CEST] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/datas/developpement/sources/Alignak-monitoring/alignak/alignak/daemons/arbiterdaemon.py", line 697, in main
    self.load_monitoring_config_file()
  File "/datas/developpement/sources/Alignak-monitoring/alignak/alignak/daemons/arbiterdaemon.py", line 475, in load_monitoring_config_file
    self.conf.prepare_for_sending()
  File "/datas/developpement/sources/Alignak-monitoring/alignak/alignak/objects/config.py", line 1472, in prepare_for_sending
    realm.serialized_confs[conf_id] = serialize(conf)
  File "/datas/developpement/sources/Alignak-monitoring/alignak/alignak/misc/serialization.py", line 47, in serialize
    o_dict['content'] = obj.serialize()
  File "/datas/developpement/sources/Alignak-monitoring/alignak/alignak/objects/config.py", line 867, in serialize
    res[prop] = getattr(self, prop).serialize()
  File "/datas/developpement/sources/Alignak-monitoring/alignak/alignak/commandcall.py", line 126, in serialize
    res['command'] = self.command.serialize()
AttributeError: 'NoneType' object has no attribute 'serialize'
```

This is because the format of the `host_perfdata_command` property value is not the expected one ...

**Comment by mohierf** [comment]
Initially created here: https://github.com/Alignak-monitoring-contrib/alignak-backend/issues/412 this issue concerns tha Alignak framework and not the Alignak backend.
