### ISSUE TITLE
Alignak stop problem if receiverd crash

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring/alignak#902]
Alignak stop problem if receiverd crash
Alignak stop  with **new** script "~/repos/alignak/dev/stop_all.sh" **VS old** script "/usr/local/etc/init.d/alignak stop"

```
[2017-08-16 11:18:46 CEST] INFO: [alignak.module.nsca] Decoded NSCA packet: host/service: ltapp226/nsca_updates, timestamp: 1502875126, output: Die Skriptausf^hrungszeit wurde bei Skript "c:\Program Files\NSClient++\scripts\lib\wrapper.vbs" ^berschritten. Di
e Skriptausf^hrung wurde abgebrochen. [2017-08-16 11:18:47 CEST] CRITICAL: [alignak.daemon] I got an unrecoverable error. I haveto exit.
[2017-08-16 11:18:47 CEST] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2017-08-16 11:18:47 CEST] CRITICAL: [alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configuration, ...
[2017-08-16 11:18:47 CEST] CRITICAL: [alignak.daemon] -----
[2017-08-16 11:18:47 CEST] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/receiverdaemon.py", line 464, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 408, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/receiverdaemon.py", line 428, in do_loop_turn
    self.push_external_commands_to_schedulers()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/receiverdaemon.py", line 388, in push_external_commands_to_schedulers
    "sending external commands: %s", sched.scheduler_name, str(exp))
AttributeError: 'dict' object has no attribute 'scheduler_name'

[2017-08-16 11:18:48 CEST] INFO: [alignak.basemodule] Process for module web-services is now exiting (pid=6542)
[2017-08-16 11:20:04 CEST] INFO: [alignak.module.nsca] Decoded NSCA packet: host/service: ltvpn101/nsca_updates, timestamp: 15028
75204, output: OK: Number of critical updates not installed: 4 Number of software updates not installed: 0
[2017-08-16 11:20:04 CEST] INFO: [alignak.basemodule] Process for module nsca is now exiting (pid=4788)

 ----  TCP         127.0.0.1  5667 NSCA
 open  TCP         127.0.0.1  8888 WServices
 open  TCP         127.0.0.1  7773 receiverd.ini
 open  TCP         127.0.0.1  7772 brokerd.ini
 open  TCP         127.0.0.1  7770 arbiterd.ini
 open  TCP         127.0.0.1  7768 schedulerd.ini
 open  TCP         127.0.0.1  7769 reactionnerd.ini
 open  TCP         127.0.0.1  7771 pollerd.ini
 open  TCP         127.0.0.1  7771 poller-master.cfg
 open  TCP         127.0.0.1  7768 scheduler-master.cfg
 open  TCP         127.0.0.1  7769 reactionner-master.cfg
 open  TCP         127.0.0.1  7772 broker-master.cfg
 open  TCP         127.0.0.1  7770 arbiter-master.cfg
 open  TCP         127.0.0.1  7773 receiver-master.cfg

```

**New script: "~/repos/alignak/dev/stop_all.sh"**
``` 
# -----------------------------------------------------------------------------
# ~/repos/alignak/dev/stop_all.sh 
# -----------------------------------------------------------------------------
 
 ----  TCP         127.0.0.1  5667 NSCA
 open  TCP         127.0.0.1  8888 WServices
 open  TCP         127.0.0.1  7773 receiverd.ini
 ----  TCP         127.0.0.1  7772 brokerd.ini
 ----  TCP         127.0.0.1  7770 arbiterd.ini
 ----  TCP         127.0.0.1  7768 schedulerd.ini
 ----  TCP         127.0.0.1  7769 reactionnerd.ini
 ----  TCP         127.0.0.1  7771 pollerd.ini
 ----  TCP         127.0.0.1  7771 poller-master.cfg
 ----  TCP         127.0.0.1  7768 scheduler-master.cfg
 ----  TCP         127.0.0.1  7769 reactionner-master.cfg
 ----  TCP         127.0.0.1  7772 broker-master.cfg
 ----  TCP         127.0.0.1  7770 arbiter-master.cfg
 open  TCP         127.0.0.1  7773 receiver-master.cfg
```
 
**Old script: "/usr/local/etc/init.d/alignak stop"** 
``` 
# -----------------------------------------------------------------------------
# /usr/local/etc/init.d/alignak stop
# -----------------------------------------------------------------------------

Alignak main configuration file is: /usr/local/etc/alignak/alignak.cfg
---
Stopping scheduler
 * Couldn't get status of scheduler: scheduler NOT RUNNING (pidfile (/usr/local/var/run/alignak/schedulerd.pid) not exist)
   ...fail!
Stopping poller
 * Couldn't get status of poller: poller NOT RUNNING (pidfile (/usr/local/var/run/alignak/pollerd.pid) not exist)
   ...fail!
Stopping reactionner
 * Couldn't get status of reactionner: reactionner NOT RUNNING (pidfile (/usr/local/var/run/alignak/reactionnerd.pid) not exist)
   ...fail!
Stopping broker
 * Couldn't get status of broker: broker NOT RUNNING (pidfile (/usr/local/var/run/alignak/brokerd.pid) not exist)
   ...fail!
Stopping receiver
   ...done.
Stopping arbiter
 * Couldn't get status of arbiter: arbiter NOT RUNNING (pidfile (/usr/local/var/run/alignak/arbiterd.pid) not exist)
   ...fail!


 ----  TCP         127.0.0.1  5667 NSCA
 ----  TCP         127.0.0.1  8888 WServices
 ----  TCP         127.0.0.1  7773 receiverd.ini
 ----  TCP         127.0.0.1  7772 brokerd.ini
 ----  TCP         127.0.0.1  7770 arbiterd.ini
 ----  TCP         127.0.0.1  7768 schedulerd.ini
 ----  TCP         127.0.0.1  7769 reactionnerd.ini
 ----  TCP         127.0.0.1  7771 pollerd.ini
 ----  TCP         127.0.0.1  7771 poller-master.cfg
 ----  TCP         127.0.0.1  7768 scheduler-master.cfg
 ----  TCP         127.0.0.1  7769 reactionner-master.cfg
 ----  TCP         127.0.0.1  7772 broker-master.cfg
 ----  TCP         127.0.0.1  7770 arbiter-master.cfg
 ----  TCP         127.0.0.1  7773 receiver-master.cfg
```

**Comment by mohierf** [comment]
I do not really understand what is the difference... the *old* `alignak` script is a Debian services start / stop script and, may be, it needs to be adapted?

**Comment by mohierf** [comment]
Fixed
