### ISSUE TITLE
Catch all daemons stop request

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#919]
When stopping the receiver daemon, sometimes we get:
```
 # cat receiverd.log
[2017-09-04 07:16:21 CEST] INFO: [alignak.basemodule] Process for module nsca received a signal: 15
[2017-09-04 07:16:21 CEST] ERROR: [alignak.basemodule] [nsca] main function exception: (4, 'Interrupted system call')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/basemodule.py", line 418, in _main
    self.main()
  File "/usr/local/lib/python2.7/site-packages/alignak_module_nsca/nsca.py", line 325, in main
    inputready, _, _ = select.select(input, [], [], 1)
error: (4, 'Interrupted system call')
```

This is not a problem because the daemon is requested to stop and it is interrupted while a system call is ongoing ... but it may be cleaner to avoid such a log 😉

**Comment by mohierf** [comment]
Fixed in the new python3 branch
