### ISSUE TITLE
Contact external command breaks the receiver daemon

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#932]
As of https://github.com/Alignak-monitoring-contrib/alignak-module-ws/issues/60.

Exception log:
```
[2017-09-21 12:53:05 CEST] INFO: [alignak.module.web-services] Got an external command: [1505991185] DISABLE_CONTACT_HOST_NOTIFICATIONS;admin
[2017-09-21 12:53:05 CEST] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2017-09-21 12:53:05 CEST] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2017-09-21 12:53:05 CEST] CRITICAL: [alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configuration, ...
[2017-09-21 12:53:05 CEST] CRITICAL: [alignak.daemon] -----
[2017-09-21 12:53:05 CEST] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 464, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 408, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 428, in do_loop_turn
    self.push_external_commands_to_schedulers()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/receiverdaemon.py", line 338, in push_external_commands_to_schedulers
    self.external_commands_manager.resolve_command(ext_cmd)
  File "/usr/local/lib/python2.7/site-packages/alignak/external_command.py", line 527, in resolve_command
    res = self.get_command_and_args(command.strip(), excmd)
  File "/usr/local/lib/python2.7/site-packages/alignak/external_command.py", line 791, in get_command_and_args
    contact = self.contacts.find_by_name(val)
AttributeError: ExternalCommandManager instance has no attribute 'contacts'
```

The problem is in the Alignak external commands manager that do not have any contacts configured ... the receiver daemon creates its manager without providing a configuration. As such, no contacts are known 😞

**Comment by mohierf** [comment]
The command `disable_contact_host_notifications` is declared as `global=True` but µGlobal commands are not managed by the current ECM if it is a *dispatcher* ECM. The ECM of the receiver daemon is a *receiver* one and, as such, it tries to manage the command, like it does for hosts and services commands ... but it does not know anything about the contacts!

**Comment by mohierf** [comment]
A specific treatment is done for the hosts and services when the External command manager is in `receiver` mode but nothing is done for the other type of objects ... this may be a solution. Else the ECM of the receiver should send its commands to its schedulers to let them handle the commands. To be confirmed ...
