### ISSUE TITLE
Scheduler exception, serialization - RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#958]
```
[2017-11-20 16:37:54 CET] INFO: [alignak.scheduler] -> 1 actions to start now
[2017-11-20 16:38:22 CET] INFO: [alignak.scheduler] -> 1 actions to start now
[2017-11-20 16:38:23 CET] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2017-11-20 16:38:23 CET] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2017-11-20 16:38:23 CET] CRITICAL: [alignak.daemon] If you think this is a bug, create a new issue including as much details as possible (version, configuration, ...
[2017-11-20 16:38:23 CET] CRITICAL: [alignak.daemon] -----
[2017-11-20 16:38:23 CET] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 443, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemon.py", line 408, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/schedulerdaemon.py", line 244, in do_loop_turn
    self.sched.run()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 2385, in run
    fun()
  File "/usr/local/lib/python2.7/site-packages/alignak/scheduler.py", line 1801, in consume_results
    self.resultmodulations, self.triggers, self.checks)
  File "/usr/local/lib/python2.7/site-packages/alignak/objects/schedulingitem.py", line 1716, in consume_result
    self.no_more_a_problem(hosts, services, timeperiods, bi_modulations)
  File "/usr/local/lib/python2.7/site-packages/alignak/objects/schedulingitem.py", line 862, in no_more_a_problem
    brok = self.get_update_status_brok()
  File "/usr/local/lib/python2.7/site-packages/alignak/objects/item.py", line 635, in get_update_status_brok
    return Brok({'type': 'update_' + self.my_type + '_status', 'data': data})
  File "/usr/local/lib/python2.7/site-packages/alignak/brok.py", line 105, in __init__
    self.data = serialize(params['data'])
  File "/usr/local/lib/python2.7/site-packages/alignak/misc/serialization.py", line 56, in serialize
    o_dict[key] = serialize(value, True)
  File "/usr/local/lib/python2.7/site-packages/alignak/misc/serialization.py", line 55, in serialize
    for key, value in obj.iteritems():
RuntimeError: dictionary changed size during iteration
```

**Comment by mohierf** [comment]
Should be fixed now
