### ISSUE TITLE
Broken SSL with default files

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#986]
With the default files used for tests (in *test_run/cfg/ssl*), SSL is broken:
```
[2018-01-07 12:07:07 CET] INFO: [scheduler-master.alignak.daemon] HTTP main thread running
[2018-01-07 12:07:07 CET] ERROR: [scheduler-master.alignak.daemon] The HTTP daemon failed with the error [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')], exiting
Traceback (most recent call last):
  File "/home/alignak/alignak/alignak/daemon.py", line 1560, in http_daemon_thread
    self.http_daemon.run()
  File "/home/alignak/alignak/alignak/http/daemon.py", line 165, in run
    self.srv.start()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 1999, in start
    self.bind(af, socktype, proto)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 2053, in bind
    self.socket = self.ssl_adapter.bind(self.socket)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/ssl_pyopenssl.py", line 180, in bind
    self.context = self.get_context()
  File "/home/alignak/alignak/alignak/http/daemon.py", line 81, in get_context
    cont.load_verify_locations(self.certificate_chain)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 775, in load_verify_locations
    _raise_current_error()
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
```

@ddurieux: any udex about this problem ?

**Comment by mohierf** [comment]
@ddurieux : pyopenssl version ?
