### ISSUE TITLE
Arbiter loading configuration exception

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#987]
Exception in the arbiter log:
```
[2018-01-17 11:31:29 CET] INFO: [alignak.module.backend_arbiter] Got 112 hosts
[2018-01-17 11:31:29 CET] INFO: [alignak.module.backend_arbiter] Got 5 hostgroups
[2018-01-17 11:31:59 CET] ERROR: [alignak.daemons.arbiterdaemon] Module backend_arbiter get_objects raised an exception Expecting ',' delimiter or '}': line 1 column 155143 (char
155142). Log and continue to run
[2018-01-17 11:31:59 CET] ERROR: [alignak.daemons.arbiterdaemon] Back trace of this remove: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/arbiterdaemon.py", line 580, in load_modules_configuration_objects
    objs = inst.get_objects()
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend-1.0.1-py2.7.egg/alignak_module_backend/arbiter/module.py", line 1170, in get_objects
    self.get_services()
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend-1.0.1-py2.7.egg/alignak_module_backend/arbiter/module.py", line 763, in get_services
    all_services = self.backend.get_all('service', params)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 402, in get_all
    resp = self.get(endpoint, params)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 341, in get
    resp = response.json()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 884, in json
    self.content.decode(encoding), **kwargs
  File "/usr/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting ',' delimiter or '}': line 1 column 155143 (char 155142)

```

**Comment by mohierf** [comment]
Fixed in the python3 branch
